# -*- coding: utf-8 -*-
"""optimization file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XZceof8kkBHjJ0QU2yaYEzX-_4nPWW_R

## **Data**

# Data simulation
"""

import numpy as np #for numerical operations
import pandas as pd #for data manipulation
from scipy.stats import beta #for beta distribution functions

# Control combination costs
control_costs = {
    1: 21314.00, 2: 14903.58, 3: 24116.60, 4: 9331.18, 5: 11105.08,
    6: 10509.62, 7: 12133.78, 8: 21739.62, 9: 12141.36, 10: 25584.56,
    11: 11044.73, 12: 9391.95, 13: 18117.89, 14: 44767.17, 15: 45863.80,
    16: 27044.94, 17: 24275.14, 18: 36956.72, 19: 45307.20, 20: 65586.44,
    21: 59711.13, 22: 61376.23, 23: 70281.10
}

# Breach type parameters
breach_params = {
    'Confidentiality': {'mean': 0.68, 'std': 0.1156},
    'Integrity': {'mean': 0.61, 'std': 0.1244},
    'Availability': {'mean': 0.51, 'std': 0.0867},
    'Authentication': {'mean': 0.66, 'std': 0.1089}
}

# Simulation parameters
n_simulations = 100
n_controls = 23
breach_types = list(breach_params.keys()) #Extracts breach type names

def get_beta_params(mean, std):
    """Calculate alpha and beta for Beta distribution"""
    var = std ** 2
    alpha = ((1 - mean) / var - 1 / mean) * mean ** 2
    beta_val = alpha * (1 / mean - 1)
    return max(0.1, alpha), max(0.1, beta_val)  #Ensures parameters are ≥ 0.1 for numerical stability

def get_linear_multiplier(control_id, max_cost, breach_type):
    """Returns linear probability scaling based on cost and breach type"""

    # Calculates a cost-based scaling factor
    cost_ratio = control_costs[control_id] / max_cost # Divides control cost by maximum cost and Returns ratio between 0 and 1 $$breach type is not used
    return cost_ratio

# Generate simulation data
sim_data = []
max_cost = max(control_costs.values())

for sim in range(1, n_simulations + 1): # Outer loop: 100 simulation iterations
    for control_id in control_costs.keys(): # Inner loop: Processes each control
        row = {
            'Iteration': sim,
            'Control_ID': control_id,
            'Cost': control_costs[control_id]
        }

        for breach, params in breach_params.items():
            alpha, beta_val = get_beta_params(params['mean'], params['std'])
            base_mult = get_linear_multiplier(control_id, max_cost, breach)

                # Standard linear pattern
            raw_prob = np.random.beta(alpha, beta_val) # Samples from beta distribution using calculated parameters
            adj_prob = base_mult * (raw_prob / params['mean']) # Adjusts probability based on cost ratio
            prob = np.clip(adj_prob, 0.05, 0.85) # Clips values to [0.05, 0.85] range

            row[breach[:4]] = round(prob, 4)

        sim_data.append(row)

# Create DataFrames
df = pd.DataFrame(sim_data) # Creates DataFrame from simulation data
column_order = ['Iteration', 'Control_ID', 'Cost'] + [b[:4] for b in breach_types]
df = df[column_order]

# Calculate average probabilities
avg_probs = df.groupby('Control_ID')[[b[:4] for b in breach_types]].mean() # Calculates average probabilities per control
avg_probs['Cost'] = [control_costs[i] for i in avg_probs.index]

# Save results
df.to_csv('linear_breach_simulation.csv', index=False) # saves Raw simulation data
avg_probs.to_csv('linear_breach_averages.csv') # Averaged results by control

# Calculate overall means
overall_means = df[[b[:4] for b in breach_types]].mean() # Prints mean probabilities across all simulations
print("\nOverall mean probabilities:")
print(overall_means)

print("\nLinear probability simulation complete!")
print(f"Main dataset shape: {df.shape}")
print("\nAverage probabilities per control (sorted by Cost):")
print(avg_probs.sort_values('Cost'))

df = pd.read_csv('linear_breach_simulation.csv')
Summary_statistics = df.describe()
Summary_statistics.to_csv('summary_statistics.csv')
Summary_statistics

import numpy as np #for numerical operations
import pandas as pd #for data manipulation
import matplotlib.pyplot as plt
import seaborn as sns

# Set style for better visuals
sns.set(style="whitegrid")
plt.figure(figsize=(15, 10))

df = pd.read_csv('linear_breach_simulation.csv')
# Create subplots for each breach type
for i, breach_type in enumerate(['Conf', 'Inte', 'Avai', 'Auth'], 1):
    plt.subplot(2, 2, i)

    # Plot histogram with KDE
    sns.histplot(df[breach_type]*100, bins=30, kde=True, color=f'C{i-1}', alpha=0.6)

    # Add vertical line at mean
    mean_val = df[breach_type].mean()*100
    plt.axvline(mean_val, color=f'C{i-1}', linestyle='--', linewidth=2,
               label=f'Mean: {mean_val:.2f}%')

    # Add vertical line at median
    median_val = df[breach_type].median()*100
    plt.axvline(median_val, color=f'C{i-1}', linestyle=':', linewidth=2,
               label=f'Median: {median_val:.2f}%')

    # Formatting
    plt.title(f'{breach_type.capitalize()} Distribution', fontsize=14)
    plt.xlabel('Probability (%)', fontsize=12)
    plt.ylabel('Frequency', fontsize=12)
    plt.legend(fontsize=10)
    plt.xlim(0, 100)

    # Add text box with key statistics
    stats_text = f"""
    Std Dev: {df[breach_type].std()*100:.2f}%
    Min: {df[breach_type].min()*100:.2f}%
    Max: {df[breach_type].max()*100:.2f}%
    """
    plt.gca().text(0.95, 0.95, stats_text, transform=plt.gca().transAxes,
                  fontsize=10, verticalalignment='top', horizontalalignment='right',
                  bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))

plt.tight_layout()
plt.suptitle('Breach Probability Distributions by Type', y=1.02, fontsize=16)
plt.savefig('breach_probability_distributions.png', dpi=300, bbox_inches='tight')
plt.show()

"""# Calculating log values"""

# converting the decimal values to probability values
import pandas as pd

#DROPING COLUMNS
summary_prob = Summary_statistics.drop(columns=['Control_ID', 'Cost', 'Iteration'])

# Convert decimal values in the summary rows (mean, std, min, max) to probability values
rows_to_convert = ['mean', 'std', 'min', '25%', '50%', '75%', 'max']

for row_index, row in summary_prob.iterrows():
    # Convert the values in the columns corresponding to breach types
    for col in summary_prob.columns[0:]: # Skip the first two columns (metric and count)
        summary_prob.at[row_index, col] = summary_prob.at[row_index, col] * 100

# Display the modified summary statistics table
print("Summary Statistics (converted to probabilities):")
summary_prob

# LOG (MEAN) AND LOG(STD)

import pandas as pd
import numpy as np
# Extract mean and std deviation from the 'summary_prob' DataFrame
mean_probs = summary_prob.loc['mean']
std_dev_probs = summary_prob.loc['std']

# Convert mean and std deviation from percentages back to decimals for log calculation
mean_decimals = mean_probs
std_dev_decimals = std_dev_probs

# Calculate Log(Mean) and Log(Std) for each breach type
log_mean = np.log(mean_decimals)
log_std = np.log(std_dev_decimals)

# Create a new DataFrame to store Log(Mean) and Log(Std)
log_stats_df = pd.DataFrame({
    'Log(Mean)': log_mean,
    'Log(Std)': log_std
})

# Rename the index to be more descriptive
log_stats_df.index.name = 'Breach Type'

print("Log(Mean) and Log(Std) from Summary Statistics:")
log_stats_df

"""#Piecewise Cofficients"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

# Load the data
avg_probs = pd.read_csv('linear_breach_averages.csv')

# Get the median cost to split into two segments
median_cost = avg_probs['Cost'].median()

# Initialize storage for coefficients in a list (easier for DataFrame conversion)
coefficients_list = []

# For each breach type, calculate piecewise linear coefficients
for breach in ['Conf', 'Inte', 'Avai', 'Auth']:
    # Prepare data
    X = avg_probs['Cost'].values.reshape(-1, 1)
    y = avg_probs[breach].values

    # Split into low and high cost segments
    low_mask = avg_probs['Cost'] <= median_cost
    high_mask = ~low_mask

    # Fit low segment
    if sum(low_mask) > 1:
        reg_low = LinearRegression()
        reg_low.fit(X[low_mask], y[low_mask])
        coefficients_list.append({
            'breach_type': breach,
            'segment': 'low',
            'cost_threshold': median_cost,
            'slope': reg_low.coef_[0]*100000,
            'intercept': reg_low.intercept_*100,
            'r_squared': reg_low.score(X[low_mask], y[low_mask])*100,
            'n_samples': sum(low_mask)
        })

    # Fit high segment
    if sum(high_mask) > 1:
        reg_high = LinearRegression()
        reg_high.fit(X[high_mask], y[high_mask])
        coefficients_list.append({
            'breach_type': breach,
            'segment': 'high',
            'cost_threshold': median_cost,
            'slope': reg_high.coef_[0]*100000,
            'intercept': reg_high.intercept_*100,
            'r_squared': reg_high.score(X[high_mask], y[high_mask])*100,
            'n_samples': sum(high_mask)
        })

# Convert to DataFrame
coefficients_df = pd.DataFrame(coefficients_list)

# Reorder columns for better readability
#column_order = [
#   'breach_type', 'segment', 'cost_threshold',
#    'slope', 'intercept', 'r_squared', 'n_samples'
#]
column_order = [
    'breach_type', 'segment', 'cost_threshold',
    'slope', 'intercept', 'r_squared']
coefficients_df = coefficients_df[column_order]

# Save to CSV
coefficients_df.to_csv('piecewise_linear_coefficients.csv', index=False)

print("Piecewise linear coefficients saved to 'piecewise_linear_coefficients.csv'")
print("\nCoefficients DataFrame:")
print(coefficients_df)

# Add some statistics to the CSV for reference
stats_df = pd.DataFrame({
    'median_cost': [median_cost],
    'min_cost': [avg_probs['Cost'].min()],
    'max_cost': [avg_probs['Cost'].max()],
    'n_controls': [len(avg_probs)]
})
stats_df.to_csv('piecewise_linear_stats.csv', index=False)

print("\nAdditional statistics saved to 'piecewise_linear_stats.csv'")

import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression # Import LinearRegression

# Calculate the cost threshold (median cost)
cost_threshold = avg_probs['Cost'].median()

# Prepare data for plotting the fitted curves
# Need to sort the costs to plot the lines correctly
x_sorted = np.sort(avg_probs['Cost'].values)
fitted_curves = {}
fitted_params = {} # Initialize fitted_params dictionary

# Create a list of the shortened breach type names
short_breach_types = ['Conf', 'Inte', 'Avai', 'Auth']

# Calculate fitted values for each breach type
for breach in short_breach_types:
    # Get the coefficients for the current breach type
    breach_coefs = coefficients_df[coefficients_df['breach_type'] == breach]

    if not breach_coefs.empty:
        # Extract coefficients for low and high segments
        coef_low = breach_coefs[breach_coefs['segment'] == 'low'].iloc[0]
        coef_high = breach_coefs[breach_coefs['segment'] == 'high'].iloc[0]

        # Calculate fitted values for both segments
        y_fit = []
        for cost in x_sorted:
            if cost <= cost_threshold:
                # Use low segment coefficients
                y_fit.append((coef_low['slope'] / 100000) * cost + (coef_low['intercept'] / 100))
            else:
                # Use high segment coefficients
                y_fit.append((coef_high['slope'] / 100000) * cost + (coef_high['intercept'] / 100))

        fitted_curves[breach] = np.array(y_fit)
        # Store parameters for annotation (optional, but good for completeness)
        fitted_params[breach] = {
            'low_slope': coef_low['slope'],
            'low_intercept': coef_low['intercept'],
            'high_slope': coef_high['slope'],
            'high_intercept': coef_high['intercept']
        }
    else:
        fitted_curves[breach] = None # Handle cases where no coefficients are found


# Plotting the results
plt.figure(figsize=(18, 12))

# Create a list of y-axis tick locations
y_ticks = np.arange(0, 1.1, 0.10) # Probabilities from 0 to 1 with 0.1 intervals


for i, breach_type_short in enumerate(short_breach_types):
    plt.subplot(2, 2, i + 1)

    # Scatter plot of the original average data
    plt.scatter(avg_probs['Cost'], avg_probs[breach_type_short], label='Average Data', alpha=0.6)

    # Plot the fitted piecewise linear curve
    if breach_type_short in fitted_curves and fitted_curves[breach_type_short] is not None:
        plt.plot(x_sorted, fitted_curves[breach_type_short], color='red', label='Piecewise Linear Fit')

        # Add annotations for parameters (optional, adjust positioning as needed)
        # params = fitted_params[breach_type_short]
        # plt.text(cost_threshold, plt.gca().get_ylim()[1], f"Low Slope: {params['low_slope']:.2f}\nHigh Slope: {params['high_slope']:.2f}",
        #          horizontalalignment='left', verticalalignment='top', fontsize=10, bbox=dict(boxstyle='round,pad=0.5', fc='white', alpha=0.8))


    # Add vertical line at the cost threshold (median cost)
    plt.axvline(x=cost_threshold, color='gray', linestyle='--', label=f'Cost Threshold: {cost_threshold:.2f}')

    plt.title(f'{breach_type_short.capitalize()} Probability vs Cost', fontsize=14)
    plt.xlabel('Cost', fontsize=12)
    plt.ylabel('Probability', fontsize=12)
    # Set y-axis ticks and limits
    plt.yticks(y_ticks)
    plt.ylim(0, 1.0)
    plt.legend()
    plt.grid(True)

plt.tight_layout()
plt.suptitle('Piecewise Linear Fitting of Breach Probabilities vs Control Costs', y=1.02, fontsize=16)
plt.savefig('piecewise_linear_fit_with_threshold.png', dpi=300, bbox_inches='tight') # Save the figure
plt.show()

import matplotlib.pyplot as plt
# Function to plot data and fitted piecewise linear segments
def plot_piecewise_fit_with_save(breach_type, x_data, y_data, median_cost, coefs):
    plt.figure(figsize=(10, 6))
    plt.scatter(x_data, y_data * 100, label=f'Average {breach_type} Probability', alpha=0.6)

    # Define points for plotting fitted lines
    x_low = x_data[x_data <= median_cost]
    x_high = x_data[x_data > median_cost]

    # Plot low segment fit
    if 'low' in coefs and x_low.size > 0:
        slope_low = coefs['low']['slope'] / 100000 # Convert back from scaled
        intercept_low = coefs['low']['intercept'] / 100 # Convert back from scaled
        y_fit_low = slope_low * x_low + intercept_low
        plt.plot(x_low, y_fit_low * 100, color='red', linestyle='--', label=f'Low Cost Fit')
        # Add annotation for low slope
        plt.text(x_low.mean(), y_fit_low.mean() * 100, f'Slope: {slope_low*100000:.6f}',
                 horizontalalignment='center', verticalalignment='bottom', color='red', fontsize=9)


    # Plot high segment fit
    if 'high' in coefs and x_high.size > 0:
        slope_high = coefs['high']['slope'] / 100000 # Convert back from scaled
        intercept_high = coefs['high']['intercept'] / 100 # Convert back from scaled
        y_fit_high = slope_high * x_high + intercept_high
        plt.plot(x_high, y_fit_high * 100, color='green', linestyle='--', label=f'High Cost Fit')
        # Add annotation for high slope
        plt.text(x_high.mean(), y_fit_high.mean() * 100, f'Slope: {slope_high*100000:.6f}',
                 horizontalalignment='center', verticalalignment='bottom', color='green', fontsize=9)

    plt.axvline(median_cost, color='gray', linestyle=':', label=f'Breakpoint_cost')


    plt.title(f'Piecewise Linear Fit for {breach_type} Probability vs. Cost', fontsize=14)
    plt.xlabel('Control Cost ($)', fontsize=12)
    plt.ylabel('Probability (%)', fontsize=12)
    plt.legend()
    plt.grid(True)

    # Save the figure
    filename = f'piecewise_linear_fit_{breach_type}.png'
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    print(f"Saved plot: {filename}")

    plt.show()

# Plot and save the fit for each breach type using the calculated coefficients
for breach_type_short in short_breach_types:
    # Find the relevant coefficients for this breach type
    breach_coefs = {}
    for _, row in coefficients_df[coefficients_df['breach_type'] == breach_type_short].iterrows():
        breach_coefs[row['segment']] = row.to_dict()

    if breach_coefs:
        plot_piecewise_fit_with_save(breach_type_short, avg_probs['Cost'], avg_probs[breach_type_short], median_cost, breach_coefs)
    else:
        print(f"No coefficients found for {breach_type_short}. Skipping plot and save.")

# plot scatter graphs for both estimated (above) and average for each breach probabilities

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

df=pd.read_csv('linear_breach_simulation.csv')
avg_probs = pd.read_csv('linear_breach_averages.csv')

# Ensure avg_probs is sorted by cost for plotting lines
avg_probs_sorted_by_cost = avg_probs.sort_values('Cost').reset_index(drop=True)

# Prepare data for plotting
breach_types_short = ['Conf', 'Inte', 'Avai', 'Auth']
colors = ['C0', 'C1', 'C2', 'C3']  # Different colors for each breach type

# Create scatter plots and regression lines for each breach type
for i, breach_type_short in enumerate(breach_types_short):
    plt.figure(figsize=(10, 7))  # Create a new figure for each breach type

    # Scatter plot of the actual simulated probabilities
    # Use the full simulation data 'df' for this
    plt.scatter(df['Cost'], df[breach_type_short], color=colors[i], label=f'Simulated Probabilities ', alpha=0.2, s=10)

    # Scatter plot of the average probabilities (calculated from simulations)
    # Use the 'avg_probs' DataFrame for this
    plt.scatter(avg_probs['Cost'], avg_probs[breach_type_short], color='black', label=f'Average Probability ', marker='o', s=50, zorder=5)


    # Fit a linear regression model to the average probabilities (sorted by cost for line plotting)
    X_avg = avg_probs_sorted_by_cost['Cost'].values.reshape(-1, 1)
    y_avg = avg_probs_sorted_by_cost[breach_type_short].values
    model = LinearRegression()
    model.fit(X_avg, y_avg)
    y_pred = model.predict(X_avg)

    # Plot the linear regression line for average probabilities
    plt.plot(X_avg, y_pred, color='red', linestyle='--', label=f'Regression line', zorder=4)


    # Add plot elements
    plt.title(f'{breach_type_short.capitalize()} Probability vs Control Cost', fontsize=16)
    plt.xlabel('Control Cost', fontsize=12)
    plt.ylabel('Probability', fontsize=12)
    plt.legend()
    plt.grid(True)

    plt.show()  # Display each plot separately



"""# **Deterministic model**"""

#!pip install gurobipy

import gurobipy as gp
from gurobipy import GRB
import numpy as np

# System parameters
K = [1, 2]  # Transaction types
L = [1, 2, 3]  # Layers (edge, fog, cloud)
N_l = {
    1: [1, 2, 3],  # Edge layer nodes
    2: [4, 5],  # Fog layer nodes
    3: [6]   # Cloud layer nodes
}
N = [n for nodes in N_l.values() for n in nodes]  # All nodes

# System-level security settings
S = {
    1: "Network firewall",
    2: "Application gateway",
    3: "RBAC",
    4: "HSRP",
    5: "IDS/IPS",
    6: "MFA",
    7: "Network firewall+Application gateway",
    8: "Network firewall+HSRP+RBAC",
    9: "Network firewall+Application gateway+RBAC+HSRP",
    10: "Network firewall+Application gateway+RBAC+MFA+IDS/IPS",
    11: "Network firewall+Application gateway+RBAC+MFA+HSRP+IDS/IPS"
}

# Node-specific security settings
NS = {
    1: "Host firewall",
    2: "mTLS",
    3: "TPM",
    4: "Host firewall+mTLS",
    5: "Host firewall+TPM+mTLS"
}

# ======================
# 3. COST PARAMETERS ($)
# ======================

# System-level control costs
C_S = {
 #   1: 0.00, # No control
    1: 13754.08, # Network firewall
    2: 11567.95,  # Application gateway
    3: 12990.0,   # RBAC
    4: 12795.6,  # HSRP (Hot Standby router protocol)
    5: 15690.0, # IDS/IPS
    6: 15544.0,  # MFA
    7: 18322.03,  # Network firewall+Application gateway
    8: 21143.68,  # Network firewall+RBAC+HSRP
    9: 24711.63,  # Network firewall+Application gateway+RBAC+HSRP
    10: 7546.03, # Network firewall+Application gateway+RBAC+MFA+IDS/IPS
    11: 35945.63 # Network firewall+Application gateway+RBAC+MFA+HSRP+IDS/IPS
}

# Node-specific control costs
C_NS = {
 #   1: 0.00, # No control
    1: 1248.72,  # Host firewall
    2: 1891.0,  # mTLS
    3: 1970.34,  # TPM
    4: 2139.72,  # Host firewall+mTLS
    5: 1237.06      # Host firewall+TPM+mTLS
}

# System parameters
D_SysNormal = {1: 30, 2: 30}
C_avail = {1: 100, 2: 100}
t_avail = 20
rho_l = {1: 90, 2: 70, 3: 55}
pi_kl = {(1,1):1, (1,2):1, (1,3):0, (2,1):1, (2,2):1, (2,3):1}

# Node capacities (Y_d^l)
Y_d = {1: 30, 2: 30, 3: 30, 4: 35, 5: 35, 6: 55}

# Breach loss amounts
r_conf = {n: 518376.5957 for n in N}  # Confidentiality breach # calculated using "2024_global cybersecurity threat dataset": average losses (in Hundred $)
r_int = {n: 518376.5957 for n in N}   # Integrity breach
r_auth = {n: 451280.0000 for n in N}  # Authentication breach

# Piecewise linear coefficients for breach probabilities

# Confidentiality breach probabilities (v_p^c)
η_conf = [0.555690/1000000, 0.517645/1000000]
ξ_conf = [45.844057/100, 45.709050/100]
w_conf = len(η_conf)

# Integrity breach probabilities (v_p^i)
η_int = [0.503994/1000000, 0.488700/1000000]
ξ_int = [42.140788/100, 41.603242/100]
w_int = len(η_int)

# Authentication breach probabilities (v_p^auth)
η_auth = [0.496404/1000000, 0.505040/1000000]
ξ_auth = [43.610619/100, 44.206732/100]
w_auth = len(η_auth)

# Availability breach probabilities (v_p^a)
η_avail = [0.513798/1000000, 0.460665/1000000]
ξ_avail = [38.362751/100, 36.70018/100]
w_avail = len(η_avail)



def solve_optimal_allocation():
    model = gp.Model("Optimal_Security_Allocation_D21")

    # Decision variables
    x_S = model.addVars(S.keys(), vtype=GRB.BINARY, name="x_S")
    x_NS = model.addVars([(l,d,j) for l in L for d in N_l[l] for j in NS.keys()], vtype=GRB.BINARY, name="x_NS")
    D_SysBreach = model.addVars(K, lb=0, name="D_SysBreach")

    # Auxiliary variables for piecewise linear approximations
    u_conf = model.addVars(N, lb=0, name="u_conf")
    u_int = model.addVars(N, lb=0, name="u_int")
    u_auth = model.addVars(N, lb=0, name="u_auth")

    # Total security cost per node
    C_total = model.addVars(N, lb=0, name="C_total")

    # Objective function
    obj = gp.quicksum(
        C_avail[k] * (D_SysNormal[k] - D_SysBreach[k]) * t_avail for k in K
    )
    obj += gp.quicksum(r_conf[d] * u_conf[d] for d in N)
    obj += gp.quicksum(r_int[d] * u_int[d] for d in N)
    obj += gp.quicksum(r_auth[d] * u_auth[d] for d in N)
    obj += gp.quicksum(C_S[i] * x_S[i] for i in S)
    obj += gp.quicksum(C_NS[j] * x_NS[l,d,j] for l in L for d in N_l[l] for j in NS)

    model.setObjective(obj, GRB.MINIMIZE)

    # Constraints

    # Piecewise linear approximations
    for d in N:
        for m in range(w_conf):
            model.addConstr(
                u_conf[d] >= (η_conf[m] * C_total[d] + ξ_conf[m]),
                f"conf_pwl_{d}_{m}"
            )
        for m in range(w_int):
            model.addConstr(
                u_int[d] >= (η_int[m] * C_total[d] + ξ_int[m]),
                f"int_pwl_{d}_{m}"
            )
        for m in range(w_auth):
            model.addConstr(
                u_auth[d] >= (η_auth[m] * C_total[d] + ξ_auth[m]),
                f"auth_pwl_{d}_{m}"
            )

    # Total security cost
    for d in N:
        model.addConstr(
            C_total[d] == gp.quicksum(C_S[i] * x_S[i] for i in S) +
            gp.quicksum(C_NS[j] * x_NS[l,d,j] for l in L for j in NS if d in N_l[l]),
            f"total_cost_{d}"
        )

    # System capacity constraints
    for l in L:
        SH_nodes = N_l[l]
        total_avail_breach_risk = gp.quicksum(
            Y_d[d] * (η_avail[0] * C_total[d] + ξ_avail[0]) for d in SH_nodes
        )

        model.addConstr(
            gp.quicksum(D_SysBreach[k] * pi_kl[k, l] for k in K) <=
            rho_l[l] - total_avail_breach_risk,
            f"capacity_{l}"
        )

    # Transaction rate limits
    for k in K:
        model.addConstr(
            D_SysBreach[k] <= D_SysNormal[k],
            f"Transaction_rates_{k}"
        )

    # One system-level security setting
    model.addConstr(
        gp.quicksum(x_S[i] for i in S) == 1,
        "one_system_setting"
    )

    # One node-specific security setting per node
    for d in N:
        model.addConstr(
            gp.quicksum(x_NS[l,d,j] for l in L for j in NS if d in N_l[l]) == 1,
            f"one_node_setting_{d}"
        )

    # Optimize the model
    model.optimize()

    # Output results
    if model.status == GRB.OPTIMAL:
        print("\n=== Optimal Security Control Allocation ===")

        # Print system-level security settings
        print("\nSystem-level security settings:")
        for i in sorted(S.keys()):
            print(f" x_S[{i}] = {int(x_S[i].x)}")

        # Print node-specific security settings by layer and node
        print("\nNode-specific security settings:")
        for l in L:
            layer_name = "Edge" if l == 1 else "Fog" if l == 2 else "Cloud"
            print(f"\n{layer_name} Layer Nodes:")
            for d in sorted(N_l[l]):
                for j in sorted(NS.keys()):
                    if (l, d, j) in x_NS:
                        print(f" x_NS[{d},{j}] = {int(x_NS[l, d, j].x)}")
                    else:
                        print(f" x_NS[{d},{j}] = 0")

        # Print system breach capacities
        print("\nSystem Breach transaction rate (D_SysBreach):")
        for k in K:
            print(f"  Transaction {k}: {D_SysBreach[k].x:.2f}")

        # Print auxiliary variables
        print("\nAuxiliary Variables:")
        print("\nConfidentiality breach probabilities (u_conf):")
        for d in N:
           print(f"  Node {d}: {u_conf[d].x/10000:.8f}")

        print("\nIntegrity breach probabilities (u_int):")
        for d in N:
           print(f"  Node {d}: {u_int[d].x/10000:.8f}")

        print("\nAuthentication breach probabilities (u_auth):")
        for d in N:
            print(f"  Node {d}: {u_auth[d].x/10000:.8f}")

        # Costs
        total_control_cost = sum(C_S[i]*x_S[i].x for i in S) + sum(C_NS[j]*x_NS[l,d,j].x for l in L for d in N_l[l] for j in NS)
        print(f"\nTotal Control Cost: ${total_control_cost:,.2f}")
        print(f"Objective Value: ${model.objVal:,.2f}")

    else:
        print("No optimal solution found")

solve_optimal_allocation()

"""# **Stochastic model**

# Parameters estimation
"""

import pandas as pd
import numpy as np

# Load the data
df = pd.read_csv('linear_breach_simulation_with_estimates.csv')

# Calculate ln(error) for each attribute
df['ln_error_Conf'] = np.log(df['Conf'] / df['Estimated_Conf'])
df['ln_error_Inte'] = np.log(df['Inte'] / df['Estimated_Inte'])
df['ln_error_Avai'] = np.log(df['Avai'] / df['Estimated_Avai'])
df['ln_error_Auth'] = np.log(df['Auth'] / df['Estimated_Auth'])

# Combine all error values
all_ln_errors = pd.concat([
    df['ln_error_Conf'],
    df['ln_error_Inte'],
    df['ln_error_Avai'],
    df['ln_error_Auth']
])


# Also calculate for each attribute separately
print("\nAttribute-specific statistics:")
for attr in ['Conf', 'Inte', 'Avai', 'Auth']:
    mean = df[f'ln_error_{attr}'].mean()
    var = df[f'ln_error_{attr}'].var()
    std = df[f'ln_error_{attr}'].std()
    print(f"{attr}: Mean = {mean:.6f}, Variance = {var:.6f}, std = {std:.6f}")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats as stats

# Load the data
df = pd.read_csv('linear_breach_simulation_with_estimates.csv')

# Calculate ln(error) for each attribute
df['ln_error_Conf'] = np.log(df['Conf'] / df['Estimated_Conf'])
df['ln_error_Inte'] = np.log(df['Inte'] / df['Estimated_Inte'])
df['ln_error_Avai'] = np.log(df['Avai'] / df['Estimated_Avai'])
df['ln_error_Auth'] = np.log(df['Auth'] / df['Estimated_Auth'])

# Create Q-Q plots for each breach type
breach_types = ['Conf', 'Inte', 'Avai', 'Auth']
#fig, axes = plt.subplots(2, 2, figsize=(12, 10))
fig, axes = plt.subplots(2, 2, figsize=(12, 10))
axes = axes.flatten()

for i, breach in enumerate(breach_types):
    stats.probplot(df[f'ln_error_{breach}'], dist="norm", plot=axes[i])
  #  axes[i].set_title(f'Q-Q Plot for ln(Error) - {breach}')
    axes[i].set_xlabel('Theoretical Quantiles')
    axes[i].set_ylabel('Sample Quantiles')

plt.tight_layout()
plt.show()



import pandas as pd
import numpy as np

# Load the CSV file
df = pd.read_csv('linear_breach_simulation_with_estimates.csv')

# Compute multiplicative errors
df['epsilon_conf'] = df['Conf'] / df['Estimated_Conf']
df['epsilon_inte'] = df['Inte'] / df['Estimated_Inte']
df['epsilon_avai'] = df['Avai'] / df['Estimated_Avai']
df['epsilon_auth'] = df['Auth'] / df['Estimated_Auth']

# Log-transform the errors
df['ln_epsilon_c'] = np.log(df['epsilon_conf'])
df['ln_epsilon_i'] = np.log(df['epsilon_inte'])
df['ln_epsilon_a'] = np.log(df['epsilon_avai'])
df['ln_epsilon_auth'] = np.log(df['epsilon_auth'])

# Compute mean and standard deviation
mean_ln_epsilon_c = df['ln_epsilon_c'].mean()
std_ln_epsilon_c = df['ln_epsilon_c'].std()

mean_ln_epsilon_i = df['ln_epsilon_i'].mean()
std_ln_epsilon_i = df['ln_epsilon_i'].std()

mean_ln_epsilon_a = df['ln_epsilon_a'].mean()
std_ln_epsilon_a = df['ln_epsilon_a'].std()

mean_ln_epsilon_auth = df['ln_epsilon_auth'].mean()
std_ln_epsilon_auth = df['ln_epsilon_auth'].std()

# Print results
print(f"Confidentiality: ln(ε_conf) ~ N({mean_ln_epsilon_c:.4f}, {std_ln_epsilon_c:.4f}^2)")
print(f"Integrity: ln(ε_inte) ~ N({mean_ln_epsilon_i:.4f}, {std_ln_epsilon_i:.4f}^2)")
print(f"Availability: ln(ε_avai) ~ N({mean_ln_epsilon_a:.4f}, {std_ln_epsilon_a:.4f}^2)")
print(f"Authentication: ln(ε_auth) ~ N({mean_ln_epsilon_auth:.4f}, {std_ln_epsilon_auth:.4f}^2)")

import numpy as np

# Given parameters from the paper
mu_c, sigma_c =  -0.017093, 0.183193
mu_i, sigma_i = -0.021868, 0.222051
mu_a, sigma_a = -0.009995, 0.205583
mu_auth, sigma_auth = -0.016538, 0.178372


# Compute E[ε] for each breach type
E_epsilon_c = np.exp(mu_c + (sigma_c**2)/2)
E_epsilon_i = np.exp(mu_i + (sigma_i**2)/2)
E_epsilon_a = np.exp(mu_a + (sigma_a**2)/2)
E_epsilon_auth = np.exp(mu_auth + (sigma_auth**2)/2)

# Print the results

print(f"E[ε_conf] : {E_epsilon_c:.6f}")
print(f"E[ε_inte] : {E_epsilon_i:.6f}")
print(f"E[ε_avail] : {E_epsilon_a:.6f}")
print(f"E[ε_auth] : {E_epsilon_auth:.6f}")

"""# Model"""

#!pip install gurobipy

import numpy as np
from scipy.stats import lognorm
import gurobipy as gp
from gurobipy import GRB

# ======================
# 1. SYSTEM PARAMETERS
# ======================

# Transaction types and system architecture
K = [1, 2]  # Transaction types
L = [1, 2, 3]  # Layers (edge=1, fog=2, cloud=3)
N_l = {
    1: [1, 2, 3],  # Edge nodes
    2: [4, 5],     # Fog nodes
    3: [6]         # Cloud node
}
N = [n for nodes in N_l.values() for n in nodes]  # All nodes

# ======================
# 2. CONTROL OPTIONS
# ======================

# System-level security settings
S = {
   # 1: "No control",
    1: "Network firewall", #(from Zhang et al., 2018)
    2: "Application gateway", #(from Zhang et al., 2018)
    3: "RBAC",
    4: "HSRP", #(from Zhang et al., 2018)
    5: "IDS/IPS", #(from Zhang et al., 2018)
    6: "MFA",
    7: "Network firewall+Application gateway",
    8: "Network firewall+HSRP+RBAC",
    9: "Network firewall+Application gateway+RBAC+HSRP",
    10: "Network firewall+Application gateway+RBAC+MFA+IDS/IPS",
    11: "Network firewall+Application gateway+RBAC+MFA+HSRP+IDS/IPS"
}

# Node-specific security settings
NS = {
  #  1: "No control",
    1: "Host firewall",
    2: "mTLS",
    3: "TPM",
    4: "Host firewall+mTLS",
    5: "Host firewall+TPM+mTLS"
}

# ======================
# 3. COST PARAMETERS ($)
# ======================

# System-level control costs
C_S = {
 #   1: 0.00, # No control
    1: 13754.08, # Network firewall
    2: 11567.95,  # Application gateway
    3: 12990.0,   # RBAC
    4: 12795.6,  # HSRP (Hot Standby router protocol)
    5: 15690.0, # IDS/IPS
    6: 15544.0,  # MFA
    7: 18322.03,  # Network firewall+Application gateway
    8: 21143.68,  # Network firewall+RBAC+HSRP
    9: 24711.63,  # Network firewall+Application gateway+RBAC+HSRP
    10: 7546.03, # Network firewall+Application gateway+RBAC+MFA+IDS/IPS
    11: 35945.63 # Network firewall+Application gateway+RBAC+MFA+HSRP+IDS/IPS
}

# Node-specific control costs
C_NS = {
 #   1: 0.00, # No control
    1: 1248.72,  # Host firewall
    2: 1891.0,  # mTLS
    3: 1970.34,  # TPM
    4: 2139.72,  # Host firewall+mTLS
    5: 1237.06      # Host firewall+TPM+mTLS
}
# ======================
# 4. SYSTEM PARAMETERS
# ======================

# Transaction parameters
D_SysNormal = {1: 30, 2: 30}  # Normal transaction rates (transactions/min)
C_avail = {1: 100, 2: 100}    # Availability breach cost per transaction
t_avail = 20                   # Time parameter (minutes)

# System capacity
#rho_l = {1: 90, 2: 80, 3: 60} # Capacity constants
rho_l = {1: 90, 2: 70, 3: 55}
pi_kl = {                      # Transaction processing matrix
    (1,1):1, (1,2):1, (1,3):0,
    (2,1):1, (2,2):1, (2,3):1
}

# Node capacities (transactions per minute)
Y_d_tx1 = {1: 30, 2: 30, 3: 30, 4: 35, 5: 35, 6: 0}
Y_d_tx2 = {1: 30, 2: 30, 3: 30, 4: 35, 5: 35, 6: 55}

# Breach loss amounts ($)
r_conf = {n: 518376.5957 for n in N}  # Confidentiality breach # 2024_global cybersecurity threat: average losses
r_int = {n: 518376.5957 for n in N}   # Integrity breach
r_auth = {n: 451280 for n in N}  # Authentication breach

# ======================
# 5. BREACH PROBABILITY PARAMETERS
# ======================

# Confidentiality breach probabilities (v_p^c)

η_conf = [0.555690/1000000, 0.517645/1000000]
ξ_conf = [45.844057/100, 45.709050/100]
w_conf = len(η_conf)

# Integrity breach probabilities (v_p^i)
η_int = [0.503994/1000000, 0.488700/1000000]
ξ_int = [42.140788/100, 41.603242/100]
w_int = len(η_int)

# Authentication breach probabilities (v_p^auth)
η_auth = [0.496404/1000000, 0.505040/1000000]
ξ_auth = [43.610619/100, 44.206732/100]
w_auth = len(η_auth)

# Availability breach probabilities (v_p^a)
η_avail = [0.513798/1000000, 0.460665/1000000]
ξ_avail = [38.362751/100, 36.70018/100]
w_avail = len(η_avail)

# Stochastic parameters
mu_a, sigma_a = -0.009995, 0.205583  # For ε_avail ~ LogNormal
E_conf = 0.999687  # Expected value of ε_conf
E_int = 1.002789   # Expected value of ε_int
E_auth = 0.999370  # Expected value of ε_auth

# ======================
# 6. SAA IMPLEMENTATION
# ======================

M = 100  # Number of scenarios
np.random.seed(42)  # For reproducibility
samples_avail = lognorm.rvs(s=sigma_a, scale=np.exp(mu_a), size=M)  # Generate ε_avail samples

# ======================
# 7. GUROBI MODEL FORMULATION
# ======================

try:
    # Initialize model
    model = gp.Model("SecurityControlAllocation")

    # =====================================
    # DECISION VARIABLES
    # =====================================

    # First-stage variables (security controls)
    x_S = model.addVars(S.keys(), vtype=GRB.BINARY, name="x_S")  # System-level
    x_NS = model.addVars([(l,d,j) for l in L for d in N_l[l] for j in NS.keys()],
                        vtype=GRB.BINARY, name="x_NS")  # Node-level

    # Auxiliary variables
    u_conf = model.addVars(N, lb=0, ub=100, name="u_conf")  # Breach probabilities
    u_int = model.addVars(N, lb=0, ub=100, name="u_int")
    u_auth = model.addVars(N, lb=0, ub=100, name="u_auth")
    C_total = model.addVars(N, lb=0, name="C_total")  # Total security cost per node

    # Second-stage variables
    D_breach = model.addVars(K, range(M), lb=0, ub=max(D_SysNormal.values()),
                            name="D_brech")
    capacity_reduction = model.addVars(range(M), name="capacity_reduction")
    effective_capacity = model.addVars(range(M), name="effective_capacity")
    total_processed = model.addVars(K, range(M), name="total_processed")

    # =====================================
    # OBJECTIVE FUNCTION
    # =====================================

    # 1. Control costs (first stage)
    control_costs = (
        gp.quicksum(C_S[i] * x_S[i] for i in S.keys()) +
        gp.quicksum(C_NS[j] * x_NS[l,d,j]
                   for l in L for d in N_l[l] for j in NS.keys())
    )

    # 2. Expected breach costs (using E[ε])
    breach_costs = (
        gp.quicksum(r_conf[d] * E_conf * u_conf[d] for d in N) +
        gp.quicksum(r_int[d] * E_int * u_int[d] for d in N) +
        gp.quicksum(r_auth[d] * E_auth * u_auth[d] for d in N)
    )

    # 3. Expected availability loss (SAA)
    avail_losses = (1/M) * gp.quicksum(
        C_avail[k] * (D_SysNormal[k] - D_breach[k,m]) * t_avail
        for k in K for m in range(M)
    )

    model.setObjective(control_costs + breach_costs + avail_losses, GRB.MINIMIZE)

    # =====================================
    # CONSTRAINTS
    # =====================================

    # Total security cost per node
    for d in N:
        model.addConstr(
            C_total[d] == (
                gp.quicksum(C_S[i] * x_S[i] for i in S.keys()) +
                gp.quicksum(C_NS[j] * x_NS[l,d,j]
                           for l in L for j in NS.keys() if d in N_l[l])
            ),
            name=f"total_cost_{d}"
        )

    # Piecewise linear breach probability functions
    for d in N:
        for m in range(w_conf):
            model.addConstr(
                u_conf[d] >= η_conf[m] * C_total[d] + ξ_conf[m],
                name=f"conf_{d}_{m}"
            )
        for m in range(w_int):
            model.addConstr(
                u_int[d] >= η_int[m] * C_total[d] + ξ_int[m],
                name=f"int_{d}_{m}"
            )
        for m in range(w_auth):
            model.addConstr(
                u_auth[d] >= η_auth[m] * C_total[d] + ξ_auth[m],
                name=f"auth_{d}_{m}"
            )

    # Scenario-specific capacity constraints
    for m in range(M):
        # Capacity reduction calculation
        capacity_reduction_tx1 = model.addVar(name=f"cap_red_tx1_{m}")
        capacity_reduction_tx2 = model.addVar(name=f"cap_red_tx2_{m}")
        model.addConstr(
            capacity_reduction_tx1 == gp.quicksum(
                Y_d_tx1[d] * (η_avail[0] * C_total[d] + ξ_avail[0]) * samples_avail[m]
                for d in N
            ),
            name=f"cap_red_tx1_{m}"
        )

        model.addConstr(
            capacity_reduction_tx2 == gp.quicksum(
                Y_d_tx2[d] * (η_avail[0] * C_total[d] + ξ_avail[0]) * samples_avail[m]
                for d in N
            ),
            name=f"cap_red_tx2_{m}"
        )

        effective_capacity_tx1 = sum(rho_l.values()) - capacity_reduction_tx1
        effective_capacity_tx2 = sum(rho_l.values()) - capacity_reduction_tx2

        # Transaction processing constraints with differentiated requirements
        for k in K:
            if k == 1:  # Tx1
                model.addConstr(
                    total_processed[k,m] == gp.quicksum(
                        D_breach[k,m] * pi_kl.get((k,l), 0) for l in L
                    ),
                    name=f"total_processed_tx1_{m}"
                )

                model.addConstr(
                    total_processed[k,m] <= effective_capacity_tx1,
                    name=f"capacity_tx1_{m}"
                )

                # for Tx1
                model.addConstr(
                    D_breach[k,m] <= D_SysNormal[k]* (effective_capacity_tx1 / (sum(rho_l.values()))),
                    name=f"cap_adj_tx1_{m}"
                )

            else:  # Tx2
                model.addConstr(
                    total_processed[k,m] == gp.quicksum(
                        D_breach[k,m] * pi_kl.get((k,l), 0) for l in L
                    ),
                    name=f"total_processed_tx2_{m}"
                )

                model.addConstr(
                    total_processed[k,m] <= effective_capacity_tx2,
                    name=f"capacity_tx2_{m}"
                )

                # for Tx2
                model.addConstr(
                    D_breach[k,m] <= D_SysNormal[k]* (effective_capacity_tx2 / (sum(rho_l.values()))),
                    name=f"cap_adj_tx2_{m}"
                )
        # Effective capacity calculation
        model.addConstr(
            effective_capacity[m] == sum(rho_l.values()) - capacity_reduction[m],
            name=f"effective_cap_{m}"
        )

    # =====================================
    # ADDITIONAL CONSTRAINTS FOR CONTROL SELECTION
    # =====================================

    # Constraint to ensure exactly one system-level control is selected
    model.addConstr(gp.quicksum(x_S[i] for i in S.keys()) == 1, name="system_control_selection")

    # Constraint to ensure exactly one node-level control is selected for each node
    for l in L:
        for d in N_l[l]:
            model.addConstr(gp.quicksum(x_NS[l,d,j] for j in NS.keys()) == 1,
                           name=f"node_control_selection_{d}")

    # =====================================
    # SOLVE THE MODEL
    # =====================================
    model.optimize()

    # =====================================
    # RESULTS PROCESSING
    # =====================================
    if model.status == GRB.OPTIMAL:
        print("STOCHASTIC OPTIMIZATION RESULTS")

        # Print security settings
        print("\nSystem-level security settings:")
        for i in sorted(S.keys()):
            print(f" x_S[{i}] = {int(x_S[i].x)}")

        for l in L:
            if l == 1:
                print("\nEdge Layer Nodes:")
            elif l == 2:
                print("\nFog Layer Nodes:")
            elif l == 3:
                print("\nCloud Layer Nodes:")

            for d in sorted(N_l[l]):
                for j in sorted(NS.keys()):
                    print(f" x_NS[{d},{j}] = {int(x_NS[l,d,j].x)}")

        # Print breach probabilities
        print("\nBREACH PROBABILITIES:")
        for d in N:
            print(f"\nNode {d}:")
            print(f"  Confidentiality: {u_conf[d].X/10000:.8f}")
            print(f"  Integrity: {u_int[d].X/10000:.8f}")
            print(f"  Authentication: {u_auth[d].X/10000:.8f}")

        # Print transaction rates by scenario
        print("\nTRANSACTION RATE VARIATION ACROSS SCENARIOS:")
        print(f"{'Scenario':<8} {'Capacity':<12} {'Tx1 Rate':<12} {'Tx2 Rate':<12}")
        for m in range(M):
           print(f"{m+1:<8} {samples_avail[m]:<12.4f}"
                  f"{D_breach[1,m].X:<12.2f} {D_breach[2,m].X:<12.2f}")

        # Calculate variation statistics
        tx1_rates = [D_breach[1,m].X for m in range(M)]
        tx2_rates = [D_breach[2,m].X for m in range(M)]

        print("\nTRANSACTION RATE STATISTICS:")
        print(f"{'Metric':<12} {'Tx1':<12} {'Tx2':<12}")
        print(f"{'Mean':<12} {np.mean(tx1_rates):<12.2f} {np.mean(tx2_rates):<12.2f}")
        print(f"{'Std Dev':<12} {np.std(tx1_rates):<12.2f} {np.std(tx2_rates):<12.2f}")
        print(f"{'Min':<12} {min(tx1_rates):<12.2f} {min(tx2_rates):<12.2f}")
        print(f"{'Max':<12} {max(tx1_rates):<12.2f} {max(tx2_rates):<12.2f}")

        # Print costs
        total_control_cost = sum(C_S[i]*x_S[i].x for i in S) + \
                           sum(C_NS[j]*x_NS[l,d,j].x for l in L for d in N_l[l] for j in NS)
        total_breach_cost = sum(r_conf[d] * E_conf * u_conf[d].X for d in N) + \
                           sum(r_int[d] * E_int * u_int[d].X for d in N) + \
                           sum(r_auth[d] * E_auth * u_auth[d].X for d in N)
        total_avail_cost = (1/M) * sum(C_avail[k] * (D_SysNormal[k] - D_breach[k,m].X) * t_avail
                          for k in K for m in range(M))

        print("\nCOST BREAKDOWN:")
        print(f"Control Costs: ${total_control_cost:,.2f}")
        print(f"Breach Costs: ${total_breach_cost:,.2f}")
        print(f"Availability Losses: ${total_avail_cost:,.2f}")
        print(f"\nTOTAL COST: ${model.ObjVal:,.2f}")

    else:
        print("\nOptimization failed with status:", model.status)
        if model.status == GRB.INFEASIBLE:
            print("Computing IIS to identify conflicting constraints...")
            model.computeIIS()
            model.write("infeasible_model.ilp")
            print("Infeasibility analysis written to 'infeasible_model.ilp'")

except gp.GurobiError as e:
    print(f"Gurobi error: {e}")
except Exception as e:
    print(f"Unexpected error: {e}")



import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np

# Assuming tx1_rates and tx2_rates are available from the previous cell's execution
# (cell_id: sdDHzQYhdl93)

# Create a figure with two subplots (one for each transaction type)
fig = make_subplots(rows=1, cols=2, subplot_titles=("Transaction 1 Rate Distribution", "Transaction 2 Rate Distribution"))

# Add histogram for Transaction 1 rates
fig.add_trace(go.Histogram(x=tx1_rates, nbinsx=20, name='Tx1'), row=1, col=1)

# Add histogram for Transaction 2 rates
fig.add_trace(go.Histogram(x=tx2_rates, nbinsx=20, name='Tx2'), row=1, col=2)

# Update layout
fig.update_layout(
    title_text="Distribution of Transaction Rates Across Scenarios",
    xaxis1=dict(title="Transaction 1 Rate (transactions/min)", range=[0, 30]),
 #   xaxis1=dict(title="Transaction 1 Rate (transactions/min)"),
    yaxis1_title="Frequency",
    xaxis2=dict(title="Transaction 2 Rate (transactions/min)", range=[0, 30]),
 #   xaxis2=dict(title="Transaction 2 Rate (transactions/min)"),
    yaxis2_title="Frequency",
    showlegend=False # Hide individual trace legends, as subplot titles are descriptive
)

# Show the figure
fig.show()

"""# **Sensitivity analysis**

# graphs showing effect of varying losses
"""

import plotly.graph_objects as go

# Data preparation
loss_amounts = ['(100,100,100)', '(1,000;1,000;1,000)', '(10,000;10,000;10,000)', '(50,000;50,000;50,000)', '(100,000;100,000;100,000)', '(518,376.5957; 518,376.5957; 451,280)', '(10,000,000;10,000,000;10,000,000)']

# Model data
det_objectives = [43951.53, 51155.52, 123195.42, 443372.76, 843594.44, 4012915.2, 8047584.59]
stoch_objectives = [54674.79, 66882.88, 188963.85, 779323.68, 999773.48, 4021116.19, 8998869.85]

# Create figure
fig = go.Figure()

# Custom text positioning function
def get_text_position(y, index, is_det):
    base_pos = 'top center' if is_det else 'bottom center'
    if index == 5:  # Custom case
        return 'middle right' if is_det else 'middle left'
    return base_pos

# Add traces with value labels that never overlap
fig.add_trace(go.Scatter(
    x=loss_amounts,
    y=det_objectives,
    name='Deterministic',
    mode='lines+markers+text',
    text=[f"${x:,.1f}" for x in det_objectives], # Removed 'K' as values are not in thousands
    textposition=[get_text_position(y, i, True) for i, y in enumerate(det_objectives)],
    textfont=dict(size=12, color='blue'),
    line=dict(color='blue', width=2.5),
    marker=dict(size=7, color='blue', symbol='circle'),
    hovertemplate='<b>Loss:</b> %{x}<br><b>Value:</b> $%{y:,.2f}<extra></extra>'
))

fig.add_trace(go.Scatter(
    x=loss_amounts,
    y=stoch_objectives,
    name='Stochastic',
    mode='lines+markers+text',
    text=[f"${x:,.1f}" for x in stoch_objectives], # Removed 'K' as values are not in thousands
    textposition=[get_text_position(y, i, True) for i, y in enumerate(stoch_objectives)],
    textfont=dict(size=12, color='red'),
    line=dict(color='red', width=2.5, dash='dot'),
    marker=dict(size=8, color='red', symbol='square'),
    hovertemplate='<b>Loss:</b> %{x}<br><b>Value:</b> $%{y:,.2f}<extra></extra>'
))

# Update layout with better value visibility
fig.update_layout(
    xaxis=dict(
        title="<b>Loss Amount (confidentiality, authentication, integrity)</b>",
        title_font=dict(size=11),
        tickfont=dict(size=10),
        tickangle=0
    ),
    yaxis=dict(
        title="<b>Objective Value (in $)</b>",
        title_font=dict(size=12),
        tickfont=dict(size=12),
    #    tickprefix="$",
        tickformat=",",
        type="log",
        range=[3.6, 7.2]  # Adjusted log scale range to fit your data better
    ),
    hovermode="x unified",
    height=600,
    width=1600,
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="center",
        x=0.5
    ),
    margin=dict(l=100, r=8, b=100, t=8, pad=8)
)

# Adjust specific labels to prevent overlap
fig.update_traces(
    textposition=[
        'top center', 'top left', 'top left',
        'top left', 'top left',
        'top left', 'top left'
    ],
    selector={'name': 'Stochastic'}
)

fig.update_traces(
    textposition=[
        'bottom center', 'bottom right', 'bottom right',
        'bottom right', 'bottom right',
        'bottom right', 'bottom center'
    ],
    selector={'name': 'Deterministic'}
)

fig.show()

# Save the figure as HTML (the most reliable method without Kaleido)
#fig.write_html("loss_vary_models.html")
#plt.savefig('loss_vary_models.png') # Save the figure

"""# effect of varying sd/mean in errors estimations"""

import numpy as np

# Given parameters from the paper
mu_c, sigma_c =  -0.017093, 0.183193
mu_i, sigma_i = -0.021868, 0.222051
mu_a, sigma_a = -0.009995, 0.205583
mu_auth, sigma_auth = -0.016538, 0.178372


# Compute E[ε] for each breach type
E_epsilon_c = np.exp(mu_c + 1.5* (sigma_c**2)/2)
E_epsilon_i = np.exp(mu_i + 1.5*(sigma_i**2)/2)
#E_epsilon_a = np.exp(mu_a + (sigma_a**2)/2)
E_epsilon_auth = np.exp(mu_auth + 1.5*(sigma_auth**2)/2)

# Print the results

print(f"E[ε_conf] : {E_epsilon_c:.6f}")
print(f"E[ε_inte] : {E_epsilon_i:.6f}")
#print(f"E[ε_avail] : {E_epsilon_a:.6f}")
print(f"E[ε_auth] : {E_epsilon_auth:.6f}")

import numpy as np
from scipy.stats import lognorm
import gurobipy as gp
from gurobipy import GRB

# ======================
# 1. SYSTEM PARAMETERS
# ======================

# Transaction types and system architecture
K = [1, 2]  # Transaction types
L = [1, 2, 3]  # Layers (edge=1, fog=2, cloud=3)
N_l = {
    1: [1, 2, 3],  # Edge nodes
    2: [4, 5],     # Fog nodes
    3: [6]         # Cloud node
}
N = [n for nodes in N_l.values() for n in nodes]  # All nodes

# ======================
# 2. CONTROL OPTIONS
# ======================

# System-level security settings
S = {
   # 1: "No control",
    1: "Network firewall", #(from Zhang et al., 2018)
    2: "Application gateway", #(from Zhang et al., 2018)
    3: "RBAC",
    4: "HSRP", #(from Zhang et al., 2018)
    5: "IDS/IPS", #(from Zhang et al., 2018)
    6: "MFA",
    7: "Network firewall+Application gateway",
    8: "Network firewall+HSRP+RBAC",
    9: "Network firewall+Application gateway+RBAC+HSRP",
    10: "Network firewall+Application gateway+RBAC+MFA+IDS/IPS",
    11: "Network firewall+Application gateway+RBAC+MFA+HSRP+IDS/IPS"
}

# Node-specific security settings
NS = {
  #  1: "No control",
    1: "Host firewall",
    2: "mTLS",
    3: "TPM",
    4: "Host firewall+mTLS",
    5: "Host firewall+TPM+mTLS"
}

# ======================
# 3. COST PARAMETERS ($)
# ======================

# System-level control costs
C_S = {
 #   1: 0.00, # No control
    1: 13754.08, # Network firewall
    2: 11567.95,  # Application gateway
    3: 12990.0,   # RBAC
    4: 12795.6,  # HSRP (Hot Standby router protocol)
    5: 15690.0, # IDS/IPS
    6: 15544.0,  # MFA
    7: 18322.03,  # Network firewall+Application gateway
    8: 21143.68,  # Network firewall+RBAC+HSRP
    9: 24711.63,  # Network firewall+Application gateway+RBAC+HSRP
    10: 7546.03, # Network firewall+Application gateway+RBAC+MFA+IDS/IPS
    11: 35945.63 # Network firewall+Application gateway+RBAC+MFA+HSRP+IDS/IPS
}

# Node-specific control costs
C_NS = {
 #   1: 0.00, # No control
    1: 1248.72,  # Host firewall
    2: 1891.0,  # mTLS
    3: 1970.34,  # TPM
    4: 2139.72,  # Host firewall+mTLS
    5: 1237.06      # Host firewall+TPM+mTLS
}

# ======================
# 4. SYSTEM PARAMETERS
# ======================

# Transaction parameters
D_SysNormal = {1: 30, 2: 30}  # Normal transaction rates (transactions/min)
C_avail = {1: 100, 2: 100}    # Availability breach cost per transaction
t_avail = 20                   # Time parameter (minutes)

# System capacity
rho_l = {1: 90, 2: 80, 3: 60} # Capacity constants
pi_kl = {                      # Transaction processing matrix
    (1,1):1, (1,2):1, (1,3):0,
    (2,1):1, (2,2):1, (2,3):1
}

# Node capacities (transactions per minute)
Y_d_tx1 = {1: 30, 2: 30, 3: 30, 4: 40, 5: 40, 6: 0}
Y_d_tx2 = {1: 30, 2: 30, 3: 30, 4: 40, 5: 40, 6: 60}

# Breach loss amounts ($)
r_conf = {n: 518376.5957 for n in N}  # Confidentiality breach # 2024_global cybersecurity threat: average losses
r_int = {n: 518376.5957 for n in N}   # Integrity breach
r_auth = {n: 451280 for n in N}  # Authentication breach

# ======================
# 5. BREACH PROBABILITY PARAMETERS
# ======================

# Confidentiality breach probabilities (v_p^c)

η_conf = [0.555690/1000000, 0.517645/1000000]
ξ_conf = [45.844057/100, 45.709050/100]
w_conf = len(η_conf)

# Integrity breach probabilities (v_p^i)
η_int = [0.503994/1000000, 0.488700/1000000]
ξ_int = [42.140788/100, 41.603242/100]
w_int = len(η_int)

# Authentication breach probabilities (v_p^auth)
η_auth = [0.496404/1000000, 0.505040/1000000]
ξ_auth = [43.610619/100, 44.206732/100]
w_auth = len(η_auth)

# Availability breach probabilities (v_p^a) - also reduced
η_avail = [0.513798/1000000, 0.460665/1000000]
ξ_avail = [38.362751/100, 36.70018/100]
w_avail = len(η_avail)

# Stochastic parameters
mu_a, sigma_a = -0.009995, 0.3084  # For ε_avail ~ LogNormal
E_conf = 1.008109  # Expected value of ε_conf
E_int = 1.015227   # Expected value of ε_int
E_auth = 1.007351  # Expected value of ε_auth

# ======================
# 6. SAA IMPLEMENTATION
# ======================

M = 100  # Number of scenarios
np.random.seed(42)  # For reproducibility
samples_avail = lognorm.rvs(s=sigma_a, scale=np.exp(mu_a), size=M)  # Generate ε_avail samples

# ======================
# 7. GUROBI MODEL FORMULATION
# ======================

try:
    # Initialize model
    model = gp.Model("SecurityControlAllocation")

    # =====================================
    # DECISION VARIABLES
    # =====================================

    # First-stage variables (security controls)
    x_S = model.addVars(S.keys(), vtype=GRB.BINARY, name="x_S")  # System-level
    x_NS = model.addVars([(l,d,j) for l in L for d in N_l[l] for j in NS.keys()],
                        vtype=GRB.BINARY, name="x_NS")  # Node-level

    # Auxiliary variables
    u_conf = model.addVars(N, lb=0, ub=100, name="u_conf")  # Breach probabilities
    u_int = model.addVars(N, lb=0, ub=100, name="u_int")
    u_auth = model.addVars(N, lb=0, ub=100, name="u_auth")
    C_total = model.addVars(N, lb=0, name="C_total")  # Total security cost per node

    # Second-stage variables
    D_breach = model.addVars(K, range(M), lb=0, ub=max(D_SysNormal.values()),
                            name="D_brech")
    capacity_reduction = model.addVars(range(M), name="capacity_reduction")
    effective_capacity = model.addVars(range(M), name="effective_capacity")
    total_processed = model.addVars(K, range(M), name="total_processed")

    # =====================================
    # OBJECTIVE FUNCTION
    # =====================================

    # 1. Control costs (first stage)
    control_costs = (
        gp.quicksum(C_S[i] * x_S[i] for i in S.keys()) +
        gp.quicksum(C_NS[j] * x_NS[l,d,j]
                   for l in L for d in N_l[l] for j in NS.keys())
    )

    # 2. Expected breach costs (using E[ε])
    breach_costs = (
        gp.quicksum(r_conf[d] * E_conf * u_conf[d] for d in N) +
        gp.quicksum(r_int[d] * E_int * u_int[d] for d in N) +
        gp.quicksum(r_auth[d] * E_auth * u_auth[d] for d in N)
    )

    # 3. Expected availability loss (SAA)
    avail_losses = (1/M) * gp.quicksum(
        C_avail[k] * (D_SysNormal[k] - D_breach[k,m]) * t_avail
        for k in K for m in range(M)
    )

    model.setObjective(control_costs + breach_costs + avail_losses, GRB.MINIMIZE)

    # =====================================
    # CONSTRAINTS
    # =====================================

    # Total security cost per node
    for d in N:
        model.addConstr(
            C_total[d] == (
                gp.quicksum(C_S[i] * x_S[i] for i in S.keys()) +
                gp.quicksum(C_NS[j] * x_NS[l,d,j]
                           for l in L for j in NS.keys() if d in N_l[l])
            ),
            name=f"total_cost_{d}"
        )

    # Piecewise linear breach probability functions
    for d in N:
        for m in range(w_conf):
            model.addConstr(
                u_conf[d] >= η_conf[m] * C_total[d] + ξ_conf[m],
                name=f"conf_{d}_{m}"
            )
        for m in range(w_int):
            model.addConstr(
                u_int[d] >= η_int[m] * C_total[d] + ξ_int[m],
                name=f"int_{d}_{m}"
            )
        for m in range(w_auth):
            model.addConstr(
                u_auth[d] >= η_auth[m] * C_total[d] + ξ_auth[m],
                name=f"auth_{d}_{m}"
            )

    # Scenario-specific capacity constraints
    for m in range(M):
        # Capacity reduction calculation
        capacity_reduction_tx1 = model.addVar(name=f"cap_red_tx1_{m}")
        capacity_reduction_tx2 = model.addVar(name=f"cap_red_tx2_{m}")
        model.addConstr(
            capacity_reduction_tx1 == gp.quicksum(
                Y_d_tx1[d] * (η_avail[0] * C_total[d] + ξ_avail[0]) * samples_avail[m]
                for d in N
            ),
            name=f"cap_red_tx1_{m}"
        )

        model.addConstr(
            capacity_reduction_tx2 == gp.quicksum(
                Y_d_tx2[d] * (η_avail[0] * C_total[d] + ξ_avail[0]) * samples_avail[m]
                for d in N
            ),
            name=f"cap_red_tx2_{m}"
        )

        effective_capacity_tx1 = sum(rho_l.values()) - capacity_reduction_tx1
        effective_capacity_tx2 = sum(rho_l.values()) - capacity_reduction_tx2

        # Transaction processing constraints with differentiated requirements
        for k in K:
            if k == 1:  # Tx1
                model.addConstr(
                    total_processed[k,m] == gp.quicksum(
                        D_breach[k,m] * pi_kl.get((k,l), 0) for l in L
                    ),
                    name=f"total_processed_tx1_{m}"
                )

                model.addConstr(
                    total_processed[k,m] <= effective_capacity_tx1,
                    name=f"capacity_tx1_{m}"
                )

                # for Tx1
                model.addConstr(
                    D_breach[k,m] <= D_SysNormal[k]* (effective_capacity_tx1 / (sum(rho_l.values()))),
                    name=f"cap_adj_tx1_{m}"
                )

            else:  # Tx2
                model.addConstr(
                    total_processed[k,m] == gp.quicksum(
                        D_breach[k,m] * pi_kl.get((k,l), 0) for l in L
                    ),
                    name=f"total_processed_tx2_{m}"
                )

                model.addConstr(
                    total_processed[k,m] <= effective_capacity_tx2,
                    name=f"capacity_tx2_{m}"
                )

                # for Tx2
                model.addConstr(
                    D_breach[k,m] <= D_SysNormal[k]* (effective_capacity_tx2 / (sum(rho_l.values()))),
                    name=f"cap_adj_tx2_{m}"
                )
        # Effective capacity calculation
        model.addConstr(
            effective_capacity[m] == sum(rho_l.values()) - capacity_reduction[m],
            name=f"effective_cap_{m}"
        )

    # =====================================
    # ADDITIONAL CONSTRAINTS FOR CONTROL SELECTION
    # =====================================

    # Constraint to ensure exactly one system-level control is selected
    model.addConstr(gp.quicksum(x_S[i] for i in S.keys()) == 1, name="system_control_selection")

    # Constraint to ensure exactly one node-level control is selected for each node
    for l in L:
        for d in N_l[l]:
            model.addConstr(gp.quicksum(x_NS[l,d,j] for j in NS.keys()) == 1,
                           name=f"node_control_selection_{d}")

    # =====================================
    # SOLVE THE MODEL
    # =====================================
    model.optimize()

    # =====================================
    # RESULTS PROCESSING
    # =====================================
    if model.status == GRB.OPTIMAL:
        print("STOCHASTIC OPTIMIZATION RESULTS")

        # Print security settings
        print("\nSystem-level security settings:")
        for i in sorted(S.keys()):
            print(f" x_S[{i}] = {int(x_S[i].x)}")

        for l in L:
            if l == 1:
                print("\nEdge Layer Nodes:")
            elif l == 2:
                print("\nFog Layer Nodes:")
            elif l == 3:
                print("\nCloud Layer Nodes:")

            for d in sorted(N_l[l]):
                for j in sorted(NS.keys()):
                    print(f" x_NS[{d},{j}] = {int(x_NS[l,d,j].x)}")

        # Print breach probabilities
        print("\nBREACH PROBABILITIES:")
        for d in N:
            print(f"\nNode {d}:")
            print(f"  Confidentiality: {u_conf[d].X/10000:.8f}")
            print(f"  Integrity: {u_int[d].X/10000:.8f}")
            print(f"  Authentication: {u_auth[d].X/10000:.8f}")

        # Print transaction rates by scenario
        print("\nTRANSACTION RATE VARIATION ACROSS SCENARIOS:")
        print(f"{'Scenario':<8} {'Capacity':<12} {'Tx1 Rate':<12} {'Tx2 Rate':<12}")
        for m in range(M):
           print(f"{m+1:<8} {samples_avail[m]:<12.4f}"
                  f"{D_breach[1,m].X:<12.2f} {D_breach[2,m].X:<12.2f}")

        # Calculate variation statistics
        tx1_rates = [D_breach[1,m].X for m in range(M)]
        tx2_rates = [D_breach[2,m].X for m in range(M)]

        print("\nTRANSACTION RATE STATISTICS:")
        print(f"{'Metric':<12} {'Tx1':<12} {'Tx2':<12}")
        print(f"{'Mean':<12} {np.mean(tx1_rates):<12.2f} {np.mean(tx2_rates):<12.2f}")
        print(f"{'Std Dev':<12} {np.std(tx1_rates):<12.2f} {np.std(tx2_rates):<12.2f}")
        print(f"{'Min':<12} {min(tx1_rates):<12.2f} {min(tx2_rates):<12.2f}")
        print(f"{'Max':<12} {max(tx1_rates):<12.2f} {max(tx2_rates):<12.2f}")

        # Print costs
        total_control_cost = sum(C_S[i]*x_S[i].x for i in S) + \
                           sum(C_NS[j]*x_NS[l,d,j].x for l in L for d in N_l[l] for j in NS)
        total_breach_cost = sum(r_conf[d] * E_conf * u_conf[d].X for d in N) + \
                           sum(r_int[d] * E_int * u_int[d].X for d in N) + \
                           sum(r_auth[d] * E_auth * u_auth[d].X for d in N)
        total_avail_cost = (1/M) * sum(C_avail[k] * (D_SysNormal[k] - D_breach[k,m].X) * t_avail
                          for k in K for m in range(M))

        print("\nCOST BREAKDOWN:")
        print(f"Control Costs: ${total_control_cost:,.2f}")
        print(f"Breach Costs: ${total_breach_cost:,.2f}")
  #      print(f"Availability Losses: ${total_avail_cost:,.2f}")
        print(f"\nTOTAL COST: ${model.ObjVal:,.2f}")

    else:
        print("\nOptimization failed with status:", model.status)
        if model.status == GRB.INFEASIBLE:
            print("Computing IIS to identify conflicting constraints...")
            model.computeIIS()
            model.write("infeasible_model.ilp")
            print("Infeasibility analysis written to 'infeasible_model.ilp'")

except gp.GurobiError as e:
    print(f"Gurobi error: {e}")
except Exception as e:
    print(f"Unexpected error: {e}")

import numpy as np

# Given parameters from the paper
mu_c, sigma_c =  -0.017093, 0.183193
mu_i, sigma_i = -0.021868, 0.222051
mu_a, sigma_a = -0.009995, 0.205583
mu_auth, sigma_auth = -0.016538, 0.178372


# Compute E[ε] for each breach type
E_epsilon_c = np.exp(1.5*mu_c + (sigma_c**2)/2)
E_epsilon_i = np.exp(1.5*mu_i + (sigma_i**2)/2)
#E_epsilon_a = np.exp(mu_a + (sigma_a**2)/2)
E_epsilon_auth = np.exp(1.5*mu_auth + (sigma_auth**2)/2)

# Print the results

print(f"E[ε_conf] : {E_epsilon_c:.6f}")
print(f"E[ε_inte] : {E_epsilon_i:.6f}")
#print(f"E[ε_avail] : {E_epsilon_a:.6f}")
print(f"E[ε_auth] : {E_epsilon_auth:.6f}")

import numpy as np
from scipy.stats import lognorm
import gurobipy as gp
from gurobipy import GRB

# ======================
# 1. SYSTEM PARAMETERS
# ======================

# Transaction types and system architecture
K = [1, 2]  # Transaction types
L = [1, 2, 3]  # Layers (edge=1, fog=2, cloud=3)
N_l = {
    1: [1, 2, 3],  # Edge nodes
    2: [4, 5],     # Fog nodes
    3: [6]         # Cloud node
}
N = [n for nodes in N_l.values() for n in nodes]  # All nodes

# ======================
# 2. CONTROL OPTIONS
# ======================

# System-level security settings
S = {
   # 1: "No control",
    1: "Network firewall", #(from Zhang et al., 2018)
    2: "Application gateway", #(from Zhang et al., 2018)
    3: "RBAC",
    4: "HSRP", #(from Zhang et al., 2018)
    5: "IDS/IPS", #(from Zhang et al., 2018)
    6: "MFA",
    7: "Network firewall+Application gateway",
    8: "Network firewall+HSRP+RBAC",
    9: "Network firewall+Application gateway+RBAC+HSRP",
    10: "Network firewall+Application gateway+RBAC+MFA+IDS/IPS",
    11: "Network firewall+Application gateway+RBAC+MFA+HSRP+IDS/IPS"
}

# Node-specific security settings
NS = {
  #  1: "No control",
    1: "Host firewall",
    2: "mTLS",
    3: "TPM",
    4: "Host firewall+mTLS",
    5: "Host firewall+TPM+mTLS"
}

# ======================
# 3. COST PARAMETERS ($)
# ======================

# System-level control costs
C_S = {
 #   1: 0.00, # No control
    1: 13754.08, # Network firewall
    2: 11567.95,  # Application gateway
    3: 12990.0,   # RBAC
    4: 12795.6,  # HSRP (Hot Standby router protocol)
    5: 15690.0, # IDS/IPS
    6: 15544.0,  # MFA
    7: 18322.03,  # Network firewall+Application gateway
    8: 21143.68,  # Network firewall+RBAC+HSRP
    9: 24711.63,  # Network firewall+Application gateway+RBAC+HSRP
    10: 7546.03, # Network firewall+Application gateway+RBAC+MFA+IDS/IPS
    11: 35945.63 # Network firewall+Application gateway+RBAC+MFA+HSRP+IDS/IPS
}

# Node-specific control costs
C_NS = {
 #   1: 0.00, # No control
    1: 1248.72,  # Host firewall
    2: 1891.0,  # mTLS
    3: 1970.34,  # TPM
    4: 2139.72,  # Host firewall+mTLS
    5: 1237.06      # Host firewall+TPM+mTLS
}

# ======================
# 4. SYSTEM PARAMETERS
# ======================

# Transaction parameters
D_SysNormal = {1: 30, 2: 30}  # Normal transaction rates (transactions/min)
C_avail = {1: 100, 2: 100}    # Availability breach cost per transaction
t_avail = 20                   # Time parameter (minutes)

# System capacity
rho_l = {1: 90, 2: 80, 3: 60} # Capacity constants
pi_kl = {                      # Transaction processing matrix
    (1,1):1, (1,2):1, (1,3):0,
    (2,1):1, (2,2):1, (2,3):1
}

# Node capacities (transactions per minute)
Y_d_tx1 = {1: 30, 2: 30, 3: 30, 4: 40, 5: 40, 6: 0}
Y_d_tx2 = {1: 30, 2: 30, 3: 30, 4: 40, 5: 40, 6: 60}

# Breach loss amounts ($)
r_conf = {n: 518376.5957 for n in N}  # Confidentiality breach # 2024_global cybersecurity threat: average losses
r_int = {n: 518376.5957 for n in N}   # Integrity breach
r_auth = {n: 451280 for n in N}  # Authentication breach

# ======================
# 5. BREACH PROBABILITY PARAMETERS
# ======================

# Confidentiality breach probabilities (v_p^c)

η_conf = [0.555690/1000000, 0.517645/1000000]
ξ_conf = [45.844057/100, 45.709050/100]
w_conf = len(η_conf)

# Integrity breach probabilities (v_p^i)
η_int = [0.503994/1000000, 0.488700/1000000]
ξ_int = [42.140788/100, 41.603242/100]
w_int = len(η_int)

# Authentication breach probabilities (v_p^auth)
η_auth = [0.496404/1000000, 0.505040/1000000]
ξ_auth = [43.610619/100, 44.206732/100]
w_auth = len(η_auth)

# Availability breach probabilities (v_p^a) - also reduced
η_avail = [0.513798/1000000, 0.460665/1000000]
ξ_avail = [38.362751/100, 36.70018/100]
w_avail = len(η_avail)

# Stochastic parameters
mu_a, sigma_a = -0.0149925, 0.205583  # For ε_avail ~ LogNormal
E_conf = 0.991179  # Expected value of ε_conf
E_int = 0.991884   # Expected value of ε_int
E_auth = 0.991141  # Expected value of ε_auth

# ======================
# 6. SAA IMPLEMENTATION
# ======================

M = 100  # Number of scenarios
np.random.seed(42)  # For reproducibility
samples_avail = lognorm.rvs(s=sigma_a, scale=np.exp(mu_a), size=M)  # Generate ε_avail samples

# ======================
# 7. GUROBI MODEL FORMULATION
# ======================

try:
    # Initialize model
    model = gp.Model("SecurityControlAllocation")

    # =====================================
    # DECISION VARIABLES
    # =====================================

    # First-stage variables (security controls)
    x_S = model.addVars(S.keys(), vtype=GRB.BINARY, name="x_S")  # System-level
    x_NS = model.addVars([(l,d,j) for l in L for d in N_l[l] for j in NS.keys()],
                        vtype=GRB.BINARY, name="x_NS")  # Node-level

    # Auxiliary variables
    u_conf = model.addVars(N, lb=0, ub=100, name="u_conf")  # Breach probabilities
    u_int = model.addVars(N, lb=0, ub=100, name="u_int")
    u_auth = model.addVars(N, lb=0, ub=100, name="u_auth")
    C_total = model.addVars(N, lb=0, name="C_total")  # Total security cost per node

    # Second-stage variables
    D_breach = model.addVars(K, range(M), lb=0, ub=max(D_SysNormal.values()),
                            name="D_brech")
    capacity_reduction = model.addVars(range(M), name="capacity_reduction")
    effective_capacity = model.addVars(range(M), name="effective_capacity")
    total_processed = model.addVars(K, range(M), name="total_processed")

    # =====================================
    # OBJECTIVE FUNCTION
    # =====================================

    # 1. Control costs (first stage)
    control_costs = (
        gp.quicksum(C_S[i] * x_S[i] for i in S.keys()) +
        gp.quicksum(C_NS[j] * x_NS[l,d,j]
                   for l in L for d in N_l[l] for j in NS.keys())
    )

    # 2. Expected breach costs (using E[ε])
    breach_costs = (
        gp.quicksum(r_conf[d] * E_conf * u_conf[d] for d in N) +
        gp.quicksum(r_int[d] * E_int * u_int[d] for d in N) +
        gp.quicksum(r_auth[d] * E_auth * u_auth[d] for d in N)
    )

    # 3. Expected availability loss (SAA)
    avail_losses = (1/M) * gp.quicksum(
        C_avail[k] * (D_SysNormal[k] - D_breach[k,m]) * t_avail
        for k in K for m in range(M)
    )

    model.setObjective(control_costs + breach_costs + avail_losses, GRB.MINIMIZE)

    # =====================================
    # CONSTRAINTS
    # =====================================

    # Total security cost per node
    for d in N:
        model.addConstr(
            C_total[d] == (
                gp.quicksum(C_S[i] * x_S[i] for i in S.keys()) +
                gp.quicksum(C_NS[j] * x_NS[l,d,j]
                           for l in L for j in NS.keys() if d in N_l[l])
            ),
            name=f"total_cost_{d}"
        )

    # Piecewise linear breach probability functions
    for d in N:
        for m in range(w_conf):
            model.addConstr(
                u_conf[d] >= η_conf[m] * C_total[d] + ξ_conf[m],
                name=f"conf_{d}_{m}"
            )
        for m in range(w_int):
            model.addConstr(
                u_int[d] >= η_int[m] * C_total[d] + ξ_int[m],
                name=f"int_{d}_{m}"
            )
        for m in range(w_auth):
            model.addConstr(
                u_auth[d] >= η_auth[m] * C_total[d] + ξ_auth[m],
                name=f"auth_{d}_{m}"
            )

    # Scenario-specific capacity constraints
    for m in range(M):
        # Capacity reduction calculation
        capacity_reduction_tx1 = model.addVar(name=f"cap_red_tx1_{m}")
        capacity_reduction_tx2 = model.addVar(name=f"cap_red_tx2_{m}")
        model.addConstr(
            capacity_reduction_tx1 == gp.quicksum(
                Y_d_tx1[d] * (η_avail[0] * C_total[d] + ξ_avail[0]) * samples_avail[m]
                for d in N
            ),
            name=f"cap_red_tx1_{m}"
        )

        model.addConstr(
            capacity_reduction_tx2 == gp.quicksum(
                Y_d_tx2[d] * (η_avail[0] * C_total[d] + ξ_avail[0]) * samples_avail[m]
                for d in N
            ),
            name=f"cap_red_tx2_{m}"
        )

        effective_capacity_tx1 = sum(rho_l.values()) - capacity_reduction_tx1
        effective_capacity_tx2 = sum(rho_l.values()) - capacity_reduction_tx2

        # Transaction processing constraints with differentiated requirements
        for k in K:
            if k == 1:  # Tx1
                model.addConstr(
                    total_processed[k,m] == gp.quicksum(
                        D_breach[k,m] * pi_kl.get((k,l), 0) for l in L
                    ),
                    name=f"total_processed_tx1_{m}"
                )

                model.addConstr(
                    total_processed[k,m] <= effective_capacity_tx1,
                    name=f"capacity_tx1_{m}"
                )

                # for Tx1
                model.addConstr(
                    D_breach[k,m] <= D_SysNormal[k]* (effective_capacity_tx1 / (sum(rho_l.values()))),
                    name=f"cap_adj_tx1_{m}"
                )

            else:  # Tx2
                model.addConstr(
                    total_processed[k,m] == gp.quicksum(
                        D_breach[k,m] * pi_kl.get((k,l), 0) for l in L
                    ),
                    name=f"total_processed_tx2_{m}"
                )

                model.addConstr(
                    total_processed[k,m] <= effective_capacity_tx2,
                    name=f"capacity_tx2_{m}"
                )

                # for Tx2
                model.addConstr(
                    D_breach[k,m] <= D_SysNormal[k]* (effective_capacity_tx2 / (sum(rho_l.values()))),
                    name=f"cap_adj_tx2_{m}"
                )
        # Effective capacity calculation
        model.addConstr(
            effective_capacity[m] == sum(rho_l.values()) - capacity_reduction[m],
            name=f"effective_cap_{m}"
        )

    # =====================================
    # ADDITIONAL CONSTRAINTS FOR CONTROL SELECTION
    # =====================================

    # Constraint to ensure exactly one system-level control is selected
    model.addConstr(gp.quicksum(x_S[i] for i in S.keys()) == 1, name="system_control_selection")

    # Constraint to ensure exactly one node-level control is selected for each node
    for l in L:
        for d in N_l[l]:
            model.addConstr(gp.quicksum(x_NS[l,d,j] for j in NS.keys()) == 1,
                           name=f"node_control_selection_{d}")

    # =====================================
    # SOLVE THE MODEL
    # =====================================
    model.optimize()

    # =====================================
    # RESULTS PROCESSING
    # =====================================
    if model.status == GRB.OPTIMAL:
        print("STOCHASTIC OPTIMIZATION RESULTS")

        # Print security settings
        print("\nSystem-level security settings:")
        for i in sorted(S.keys()):
            print(f" x_S[{i}] = {int(x_S[i].x)}")

        for l in L:
            if l == 1:
                print("\nEdge Layer Nodes:")
            elif l == 2:
                print("\nFog Layer Nodes:")
            elif l == 3:
                print("\nCloud Layer Nodes:")

            for d in sorted(N_l[l]):
                for j in sorted(NS.keys()):
                    print(f" x_NS[{d},{j}] = {int(x_NS[l,d,j].x)}")

        # Print breach probabilities
        print("\nBREACH PROBABILITIES:")
        for d in N:
            print(f"\nNode {d}:")
            print(f"  Confidentiality: {u_conf[d].X/10000:.8f}")
            print(f"  Integrity: {u_int[d].X/10000:.8f}")
            print(f"  Authentication: {u_auth[d].X/10000:.8f}")

        # Print transaction rates by scenario
        print("\nTRANSACTION RATE VARIATION ACROSS SCENARIOS:")
        print(f"{'Scenario':<8} {'Capacity':<12} {'Tx1 Rate':<12} {'Tx2 Rate':<12}")
        for m in range(M):
           print(f"{m+1:<8} {samples_avail[m]:<12.4f}"
                  f"{D_breach[1,m].X:<12.2f} {D_breach[2,m].X:<12.2f}")

        # Calculate variation statistics
        tx1_rates = [D_breach[1,m].X for m in range(M)]
        tx2_rates = [D_breach[2,m].X for m in range(M)]

        print("\nTRANSACTION RATE STATISTICS:")
        print(f"{'Metric':<12} {'Tx1':<12} {'Tx2':<12}")
        print(f"{'Mean':<12} {np.mean(tx1_rates):<12.2f} {np.mean(tx2_rates):<12.2f}")
        print(f"{'Std Dev':<12} {np.std(tx1_rates):<12.2f} {np.std(tx2_rates):<12.2f}")
        print(f"{'Min':<12} {min(tx1_rates):<12.2f} {min(tx2_rates):<12.2f}")
        print(f"{'Max':<12} {max(tx1_rates):<12.2f} {max(tx2_rates):<12.2f}")

        # Print costs
        total_control_cost = sum(C_S[i]*x_S[i].x for i in S) + \
                           sum(C_NS[j]*x_NS[l,d,j].x for l in L for d in N_l[l] for j in NS)
        total_breach_cost = sum(r_conf[d] * E_conf * u_conf[d].X for d in N) + \
                           sum(r_int[d] * E_int * u_int[d].X for d in N) + \
                           sum(r_auth[d] * E_auth * u_auth[d].X for d in N)
        total_avail_cost = (1/M) * sum(C_avail[k] * (D_SysNormal[k] - D_breach[k,m].X) * t_avail
                          for k in K for m in range(M))

        print("\nCOST BREAKDOWN:")
        print(f"Control Costs: ${total_control_cost:,.2f}")
        print(f"Breach Costs: ${total_breach_cost:,.2f}")
  #      print(f"Availability Losses: ${total_avail_cost:,.2f}")
        print(f"\nTOTAL COST: ${model.ObjVal:,.2f}")

    else:
        print("\nOptimization failed with status:", model.status)
        if model.status == GRB.INFEASIBLE:
            print("Computing IIS to identify conflicting constraints...")
            model.computeIIS()
            model.write("infeasible_model.ilp")
            print("Infeasibility analysis written to 'infeasible_model.ilp'")

except gp.GurobiError as e:
    print(f"Gurobi error: {e}")
except Exception as e:
    print(f"Unexpected error: {e}")

"""# plotting

# Impact of costs on control selection
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Data preparation
control_patterns = {
    'rate_value': [-50, -40, -30, -20, -10, 0, 10, 20, 30, 40, 50],
    'stoch_sys': ['NF+AG+RBAC+HSRP+MFA+IDS', 'NF+AG+RBAC+HSRP+MFA+IDS', 'NF+RBAC+HSRP+MFA',
                 'NF+RBAC+HSRP+MFA', 'NF+RBAC+HSRP+MFA', 'NF+RBAC+HSRP+MFA',
                 'NF+AG+RBAC+HSRP', 'NF+AG', 'NF+AG', 'NF+AG', 'NF+AG'],
    'stoch_node': ['HF+TPM+mTLS', 'HF+TPM+mTLS', 'HF+TPM+mTLS', 'HF+TPM+mTLS',
                  'HF+TPM+mTLS', 'HF+TPM+mTLS', 'HF+mTLS', 'HF+mTLS', 'HF+mTLS', 'HF', 'HF'],
    'det_sys': ['NF+AG+RBAC+HSRP+MFA+IDS', 'NF+AG+RBAC+HSRP+MFA+IDS', 'NF+AG+RBAC+HSRP+MFA+IDS',
               'NF+AG+RBAC+HSRP+MFA+IDS', 'NF+RBAC+HSRP+MFA', 'NF+RBAC+HSRP+MFA',
               'NF+AG+RBAC+HSRP', 'NF+RBAC+HSRP', 'NF+RBAC+HSRP', 'NF+AG', 'NF+AG'],
    'det_node': ['HF+TPM+mTLS', 'HF+TPM+mTLS', 'HF+TPM+mTLS', 'HF+TPM+mTLS',
                'HF+TPM+mTLS', 'HF+TPM+mTLS', 'HF+mTLS', 'mTLS', 'mTLS', 'HF', 'HF']
}

control_df = pd.DataFrame(control_patterns)

# Create numerical mappings
sys_complexity = {
    'NF+AG': 1,
    'NF+RBAC+HSRP': 2,
    'NF+AG+RBAC+HSRP': 3,
    'NF+RBAC+HSRP+MFA': 4,
    'NF+AG+RBAC+HSRP+MFA+IDS': 5
}

node_complexity = {
    'HF': 1,
    'mTLS': 1.5,
    'HF+mTLS': 2,
    'HF+TPM+mTLS': 3
}

# Apply mappings
control_df['stoch_sys_num'] = control_df['stoch_sys'].map(sys_complexity)
control_df['stoch_node_num'] = control_df['stoch_node'].map(node_complexity)
control_df['det_sys_num'] = control_df['det_sys'].map(sys_complexity)
control_df['det_node_num'] = control_df['det_node'].map(node_complexity)

# Set up the figure
plt.figure(figsize=(16, 8))

# 1. Stochastic Model Comparison
plt.subplot(1, 2, 1)
bar_width = 3
x = control_df['rate_value']

# System controls
bars_sys = plt.bar(x - bar_width/2, control_df['stoch_sys_num'],
                  width=bar_width, color='royalblue', alpha=0.7, label='System-Level')

# Node controls
bars_node = plt.bar(x + bar_width/2, control_df['stoch_node_num'],
                   width=bar_width, color='lightseagreen', alpha=0.7, label='Node-Level')

# Customization
#plt.title('Stochastic Model: System vs Node-Level Controls', pad=20)
plt.xlabel('Discount/Premium Rate (%)', labelpad=10)
plt.ylabel('Control Complexity', labelpad=10)
plt.xticks(x)
plt.yticks([1, 1.5, 2, 3, 4, 5],
           ['NF+AG (system-specific)/HF (node-specific)', '', 'HF+ mTLS (node-specific)', 'HF+TPM+mTLS (host-specific)/ NF+AG+RBAC+HSRP(system-specific)', 'NF+RBAC+HSRP+MFA(system-specific)', 'NF+AG+RBAC+MFA+HSRP+IDS/IPS(system-specific)'])
plt.axvline(x=0, color='gray', linestyle='--', linewidth=1)
plt.grid(True, axis='y', alpha=0.3)
plt.legend(loc='upper right')

# Add value labels
for bar, val in zip(bars_sys, control_df['stoch_sys']):
    plt.text(bar.get_x() + bar.get_width()/2., bar.get_height()+0.1, val,
             ha='center', va='bottom', rotation=90, fontsize=8)

for bar, val in zip(bars_node, control_df['stoch_node']):
    plt.text(bar.get_x() + bar.get_width()/2., bar.get_height()+0.1, val,
             ha='center', va='bottom', rotation=90, fontsize=8)

plt.tight_layout()
plt.show()

# Set up the figure
plt.figure(figsize=(18, 10), facecolor='white')
# Removed plt.style.use('seaborn-whitegrid')

# 2. Deterministic Model Comparison
plt.subplot(1, 2, 2)

# System controls (darker colors)
bars_sys = plt.bar(x - bar_width/2, control_df['det_sys_num'],
                   width=bar_width, color='crimson', alpha=0.7, label='System-Level security controls')
     #             width=bar_width, color='#8e44ad', alpha=0.8, label='System-Level')  # Purple color

# Node controls (lighter colors)
bars_node = plt.bar(x + bar_width/2, control_df['det_node_num'],
                   width=bar_width, color='#f39c12', alpha=0.8, label='Node-Level security controls')  # Orange color

# Customization
#plt.title('Deterministic Model: Control Selection Complexity', pad=20, fontweight='bold')
plt.xlabel('Discount/Premium Rate (%)', labelpad=10)
plt.ylabel('Control Complexity Level', labelpad=10)
plt.xticks(x)
#plt.yticks([1, 1.5, 2, 3, 4, 5],
   #        ['Basic', 'mTLS', 'HF+mTLS', 'HF+TPM+mTLS', 'NF+RBAC+HSRP+MFA', 'Full Suite'])
plt.yticks([1, 1.5, 2, 3, 4, 5],
           ['HF/NF+AG', 'mTLS', 'HF+mTLS', 'HF+TPM+mTLS/NF+AG+RBAC+HSRP', 'NF+RBAC+HSRP+MFA', 'NF+AG+RBAC+MFA+HSRP+IDS/IPS'])
plt.axvline(x=0, color='gray', linestyle='--', linewidth=1)
plt.grid(True, axis='y', alpha=0.3)

# Add value labels INSIDE the bars
for bar, val in zip(bars_sys, control_df['det_sys']):
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height/2, val,
             ha='center', va='center',
             color='black',  # White text for dark bars
             fontsize=9,
             rotation=90,
        #     fontweight='bold'
             )

for bar, val in zip(bars_node, control_df['det_node']):
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height/2, val,
             ha='center', va='center',
             color='black',  # Black text for light bars
             fontsize=9,
             rotation=90,
        #     fontweight='bold'
             )

# Add legend outside the plot
plt.legend(bbox_to_anchor=(1.02, 1), loc='upper left')


plt.tight_layout()
plt.show()

"""# impact of costs on breach probabilities"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Sample data
data = {
    'rate_value': [-50, -40, -30, -20, -10, 0, 10, 20, 30, 40, 50],
    'stoch_conf': [0.00005551, 0.00005575, 0.00005554, 0.00005572, 0.00005591, 0.00005605,
                  0.00005607, 0.00005545, 0.00005555, 0.00005558, 0.00005568],
    'stoch_int': [0.00004885, 0.00004905, 0.00004888, 0.00004903, 0.00004919, 0.00004932,
                 0.00004933, 0.00004879, 0.00004888, 0.00004891, 0.00004899],
    'stoch_auth': [0.00005209, 0.00005230, 0.00005212, 0.00005228, 0.00005244, 0.00005257,
                  0.00005259, 0.00005204, 0.00005213, 0.00005215, 0.00005224],
    'det_conf': [0.00004464, 0.00004444, 0.00004424, 0.00004404, 0.00004431, 0.00004419,
                0.00004417, 0.00004487, 0.00004479, 0.00004459, 0.00004450],
    'det_int': [0.00004105, 0.00004087, 0.00004069, 0.00004051, 0.00004075, 0.00004064,
               0.00004062, 0.00004125, 0.00004119, 0.00004100, 0.00004093],
    'det_auth': [0.00004312, 0.00004293, 0.00004275, 0.00004257, 0.00004281, 0.00004270,
                0.00004269, 0.00004332, 0.00004325, 0.00004307, 0.00004299]
}

df = pd.DataFrame(data)

# Set up the figure
plt.figure(figsize=(18, 10), facecolor='white')
# Removed plt.style.use('seaborn-whitegrid')

# Custom color palette
stoch_colors = ['#3498db', '#2ecc71', '#e74c3c']  # Blue, Green, Red
det_colors = ['#85c1e9', '#82e0aa', '#f1948a']    # Light blue, Light green, Light red

# Function to format decimal values
def format_decimal(x):
    return f"{x:.8f}".rstrip('0').rstrip('.') if '.' in f"{x:.8f}" else f"{x:.8f}"

# Plot Stochastic Model
for i, (col, label) in enumerate(zip(['stoch_conf', 'stoch_int', 'stoch_auth'],
                                    ['Confidentiality', 'Integrity', 'Authenticity'])):
    plt.plot(df['rate_value'], df[col],
             color=stoch_colors[i],
             linestyle='-',
             marker='o',
             markersize=10,
             linewidth=3,
             alpha=0.9,
             label=f'Stoch {label}',
             markeredgecolor='white',
             markeredgewidth=1.5,
             zorder=3)

    # Add all values in black without boxes
    for x, y in zip(df['rate_value'], df[col]):
        plt.text(x, y, format_decimal(y),
                 color='black',  # Changed to black
                 fontsize=11,
                 ha='center',
                 va='bottom' if y > df[col].median() else 'top',
                 zorder=4)

# Plot Deterministic Model
for i, (col, label) in enumerate(zip(['det_conf', 'det_int', 'det_auth'],
                                    ['Confidentiality', 'Integrity', 'Authenticity'])):
    plt.plot(df['rate_value'], df[col],
             color=det_colors[i],
             linestyle='--',
             marker='s',
             markersize=8,
             linewidth=2.5,
             alpha=0.9,
             label=f'Det {label}',
             markeredgecolor='white',
             markeredgewidth=1.5,
             zorder=2)

    # Add all values in black without boxes
    for x, y in zip(df['rate_value'], df[col]):
        plt.text(x, y, format_decimal(y),
                 color='black',  # Changed to black
                 fontsize=11,
                 ha='center',
                 va='bottom' if y > df[col].median() else 'top',
                 zorder=4)

# Customization
#plt.title('Breach Probability Comparison\nStochastic vs Deterministic Security Models',
   #       pad=20, fontsize=14, fontweight='bold')
plt.xlabel('Discount/Premium Rate (%)', fontsize=12, labelpad=10)
plt.ylabel('Breach Probability', fontsize=12, labelpad=10)
plt.axvline(x=0, color='gray', linestyle='--', linewidth=1, alpha=0.7, zorder=1)

# Add shaded regions for discount/premium areas
plt.axvspan(-50, 0, facecolor='#eaf2f8', alpha=0.2, zorder=0)
plt.axvspan(0, 50, facecolor='#f9ebea', alpha=0.2, zorder=0)
#plt.text(-25, plt.gca().get_ylim()[1]*0.97,
  #       ha='center', va='top', fontsize=11, color='#2980b9', alpha=0.9, fontweight='bold')
#plt.text(25, plt.gca().get_ylim()[1]*0.97,
#         ha='center', va='top', fontsize=11, color='#c0392b', alpha=0.9, fontweight='bold')

# Format y-axis to show full decimal values
plt.gca().yaxis.set_major_formatter(plt.FormatStrFormatter('%.8f'))
plt.grid(True, which='both', alpha=0.4)

# Create custom legend
from matplotlib.lines import Line2D
legend_elements = [
    Line2D([0], [0], color='gray', lw=3, label='Stochastic', linestyle='-'),
    Line2D([0], [0], color='gray', lw=2.5, label='Deterministic', linestyle='--'),
    Line2D([0], [0], marker='o', color='w', label='Confidentiality',
          markerfacecolor=stoch_colors[0], markersize=11, markeredgecolor='white'),
    Line2D([0], [0], marker='o', color='w', label='Integrity',
          markerfacecolor=stoch_colors[1], markersize=11, markeredgecolor='white'),
    Line2D([0], [0], marker='o', color='w', label='Authenticity',
          markerfacecolor=stoch_colors[2], markersize=11, markeredgecolor='white')
]

plt.legend(handles=legend_elements, loc='upper center',
           bbox_to_anchor=(0.5, -0.12), ncol=5, fontsize=12, framealpha=1)

# Adjust layout and add footnote
plt.tight_layout()


plt.show()

"""# Impact of varying cost on Cybersecurity spending


"""

import matplotlib.pyplot as plt
import numpy as np

price_multipliers = [-50, -40, -30, -20, -10, 0, 10, 20, 30, 40, 50]
deterministic_costs = [27696.49, 32366.58, 36928.68, 41544.77, 37761.26, 40968.39,
                       41219.90, 22844.12, 24601.36, 31110.48, 33184.51]
stochastic_costs = [27696.49, 32366.58, 36928.68, 33985.13, 37761.26, 40968.39,
                    41219.90, 33280.42, 35840.44, 31110.48, 33184.51]

# Create figure with adjusted size
fig, ax = plt.subplots(figsize=(16, 8))

# Plot both lines with markers
line_det, = ax.plot(price_multipliers, deterministic_costs, 'b-o',
                   label='Deterministic', linewidth=2, markersize=10)
line_stoch, = ax.plot(price_multipliers, stochastic_costs, 'r--s',
                     label='Stochastic', linewidth=2, markersize=8)

# Add cost values above each point with alternating vertical offsets
for i, (x, y_det, y_stoch) in enumerate(zip(price_multipliers, deterministic_costs, stochastic_costs)):
    # Deterministic values (positioned above)
    ax.text(x, y_det + 500, f'${y_det/1000:.1f}K',
           ha='center', va='bottom', fontsize=9, color='blue',
           bbox=dict(facecolor='white', alpha=0.8, edgecolor='none', pad=1))

    # Stochastic values (positioned higher)
    ax.text(x, y_stoch + 1500, f'${y_stoch/1000:.1f}K',
           ha='center', va='bottom', fontsize=9, color='red',
           bbox=dict(facecolor='white', alpha=0.8, edgecolor='none', pad=1))

# Highlight zones
ax.axvspan(0, 50, alpha=0.05, color='red', label='Premium Zone')
ax.axvspan(-50, 0, alpha=0.05, color='green', label='Discount Zone')

# Annotate key behaviors
#ax.annotate('Dangerous Cost Cutting', xy=(20, 22844), xytext=(5, 18000),
#           arrowprops=dict(arrowstyle='->', color='black', linewidth=1),
#           bbox=dict(boxstyle='round,pad=0.5', fc='white', alpha=0.9),
#           fontsize=10, ha='center')

#ax.annotate('Risk-Adjusted Spending', xy=(20, 33280), xytext=(30, 38000),
#           arrowprops=dict(arrowstyle='->', color='black', linewidth=1),
#           bbox=dict(boxstyle='round,pad=0.5', fc='white', alpha=0.9),
#           fontsize=10, ha='center')

# Formatting
ax.set_xlabel('Price Multiplier (%)', fontsize=12, labelpad=10)
ax.set_ylabel('Security Spend ($)', fontsize=12, labelpad=10)
#ax.set_title('Cybersecurity Spending Under Price Variations', fontsize=14, pad=20)
ax.grid(True, alpha=0.2)
ax.legend(loc='upper right', fontsize=10)

# Adjust y-axis limits to accommodate value labels
ax.set_ylim(20000, 45000)

plt.tight_layout()
plt.show()

"""# **Q-Q PLOTS**"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats as stats

# Load the data
df = pd.read_csv('linear_breach_simulation_with_estimates.csv')

# Calculate ln(error) for each attribute
df['ln_error_Conf'] = np.log(df['Conf'] / df['Estimated_Conf'])
df['ln_error_Inte'] = np.log(df['Inte'] / df['Estimated_Inte'])
df['ln_error_Avai'] = np.log(df['Avai'] / df['Estimated_Avai'])
df['ln_error_Auth'] = np.log(df['Auth'] / df['Estimated_Auth'])

# Create Q-Q plots for each breach type
breach_types = ['Conf', 'Inte', 'Avai', 'Auth']
fig, axes = plt.subplots(2, 2, figsize=(12, 10))
axes = axes.flatten()

for i, breach in enumerate(breach_types):
    stats.probplot(df[f'ln_error_{breach}'], dist="norm", plot=axes[i], fit=False) # Removed fit=True
    axes[i].set_title(f'Q-Q Plot for ln(Error) - {breach}')
    axes[i].set_xlabel('Theoretical Quantiles')
    axes[i].set_ylabel('Sample Quantiles')

plt.tight_layout()
plt.savefig('qq_plots.png') # Save the figure
plt.show()